### ISSUE TITLE
Alexa could not find devices

### ISSUE THREAD

**Issue by tonyc770** [hardillb/node-red-alexa-home-skill-web#1]
I set up node red to use the alexa Home node with my account, etc.
I also set up a simple LED device to turn on/off on the site.
When I use the EchoSim.io to test for devices, Alexa reports back there are no devices.

In my node red alexa node it shows my LED device.

Why does Alexa not recognize my device?

**Comment by hardillb** [comment]
The skill has not been made public yet, so you can not add it to your device in the Alexa Mobile App. Until you add the skill it will not be able to discover your devices

**Comment by hardillb** [comment]
The skill is now live if you want to have another go

**Comment by tonyc770** [comment]
Cool, thanks I will check it out this weekend... 
  
-Tony 

----- Original Message -----
