### ISSUE TITLE
Skill not enabling on alexa

### ISSUE THREAD

**Issue by andyuk5** [hardillb/node-red-alexa-home-skill-web#10]
Hi
I have followed your instructions but unable to enable skill on my Alexa account. I must be doing something wrong.

Regards

Andyuk

**Comment by hardillb** [comment]
You're going to have to supply a LOT more information if you want some help. Explain clearly what is not working and the exact steps you have followed in as much detail as you can.

**Comment by andyuk5** [comment]
Hi Ben

Thank you for coming back to me.
I have got an account on your node red home skill bridge and setup some devices. I have installed you node in to my node red.
All seems to work but can not see my devices in drop down list.

When i go to enable your skill in my alexa app it asks for my use name which is already shown and also my password.
This is tbe user name and password i used when setting up my account on your node red site.

I do nit get an error i judt show the enable button for me to start again as if i had not pressed it.

Regards

Andyuk5

On 1 May 2017 12:20, Ben Hardill <notifications@github.com> wrote:

You're going to have to supply a LOT more information if you want some help. Explain clearly what is not working and the exact steps you have followed in as much detail as you can.

**Comment by hardillb** [comment]
What device are you trying to enable skill on? It should be in an embedded webview with in the Alexa app so shouldn't be able to pre-fill your username/password

Also if you get redirected back to the authorise page it should show an error message across the top of the screen.

**Comment by andyuk5** [comment]
Hi

I am using this with a raspberry pi 3 and have alexa app on my phone. It is redirecting me to.
https://alexa-node-red.bm.hardill.me.uk/auth/start?client_id=1&response_type=code&state=eyJpbml0VmVjdG9yIjoiZDNEcXBBeGY4YUovbDFXWDh0V0JIdz09IiwicGF5bG9hZCI6IlU4MHNSS2lpS1AwM2xZVEF0WnhOeWZIbUxZY1VTSVdscEZSNUpLOVhweEdjbll3UHg2RW1qMVlMSEI0Y1dFMEoxdFo5QnIrTWRhVzd2d01EN2lQMWpXYjVWV2VqNjFSd3I2QWQzeG03UXIwaU9xTXhKWXNJVSt3ZGYrT2ZNdnJReDBGNXV6MC94aHpxbzg5cUM1aVBGbjdFWkcvWFZwbTVSN2NvbWVFakpIdWRQaVpmWWw0Z2FLYWlxcG9FZDNJbzFUeVhYV1hPVHZzWTR3R3pMckhTclRZMXR5QUZyV1dqa3o4d21JaGVDU2VIN2hYSjhCUTJpSmlhd1dqT0VFRXFINVRXcWFRUlVzSXZnOWdhV1ZDWVVSNzF5VndlVitYSGR6ck1jZkQrWkhCY0tOYkxlNTUwckZFcXNhUlRiNGRQSmxFNmdoK2RGOHdMVi9uWUovb2c3a055TnZQZktiOU5iM3U3M2VyV1ZacnlwUExoUzB4Mnl1TTdrL1ZFaUdrMit3Q0t6L1pkTFJJSElidnpGRFhmZU02ZWJiYjA3c3RROFN6ejcyNEd3dlJHZytvZDltcm9vOXd0WW5XbXpQSUlIOFJJYnFBQnAwQXpxNHRjZmlycG1MVlF3RWhDZWlYZ1Vid2V4ZWlISDJrUHRLUkl1RVF6L0hPTEpaRWFZMWx4SnpiejVBNm5NNE5uNEJaa0FneEk2TFdqUllRaDcyQzgrYkkzZzlsK0o1K09rYi9CS1J3N1dFTXhpbHZESWd1eC84azRYS3NZeTVPMTZmR1JQc1NxS0ZoUDRBbmNWSUFPVHRFVVpVc0hzbnNkb0R2S2lZK0ZhbTVRSVViNkJ0bG1idmFHTm8wNlpqNWhWaWl4aVU3OTdtNnJwbEV4aW1VQjVxdit3c2tJS2lZWVVVdjBzN3cvSkFUWFpHam5WZE9yak5lOTZDYm45ZVI5NlRiZWpnQ2swbHBHSHlWNXF3dXpUSmJLdWg1RnU3MUtqbmtoMUpPM2VNUFRlSlh6MFRIcVdGRGFsL2RNZTBJbGYva3VZZXdFMHlVV1N2THFGb25UbVd1c2VtT3ptdmQ2NWlSNFlxL3VGT1ZzZElPYVRsdURWSTRXRTRXRnJMdWc3dFlLMXdHbERXVVRMcjZtMWpBYTNrVk8reW9FSUxlM0MwRGxPOEYrYzBYNlpUdVJwZytHIiwidmVyc2lvbiI6MX0&scope=access_devices&redirect_uri=https%3A%2F%2Flayla.amazon.com%2Fapi%2Fskill%2Flink%2FM1JDJFTBFPO0EJ

Where i put ny user name and password i setup on your website. But as soon as i click button i am back on the alexa app enable page with button not enabled and no error message.


Regards

Andyuk5


On 1 May 2017 13:19, Ben Hardill <notifications@github.com> wrote:

What device are you trying to enable skill on? It should be in an embedded webview with in the Alexa app so shouldn't be able to pre-fill your username/password

Also if you get redirected back to the authorise page it should show an error message across the top of the screen.

**Comment by hardillb** [comment]
Sounds like Amazon have changed their app, as you should never see that URL as it was in a WebView inside the app. If it's now sending you out to full blown Safari that is new.

It should ask you for the username and password, then hit the authorise button. As the only things you can enter are the username as password, if you get those wrong it will send you back but it will tell you you've got them wrong like this:

![screenshot from 2017-05-01 17 49 50](https://cloud.githubusercontent.com/assets/1800845/25586306/ab13f174-2e96-11e7-8f3f-b3cb2ec7682e.png)

If it succeeds then it should send you straight back to the Amazon app with no other interactions.

**Comment by pckhib** [comment]
I'm having the same problem. After I clicked the activate button in the Alexa Skills section, it opens a window where I have to authorise myself. After I inserted my credentials and pressed the button, it redirects to an url that starts with layla.amazon.com/api/skill/link/... but nothing happens.

**Comment by hardillb** [comment]
@pckhib I'm guessing because I can't see the comment anymore on here you deleted it? If it redirected to a URL starting http://layla.amazon.com then it probably would have been an issue on the Amazon side of things.

@andyuk5 While I'm away I can't track down the issue you are seeing. Can you try and enable the skill by logging into here: http://alexa.amazon.co.uk/spa/index.html and see if you can authorise it from there

**Comment by andyuk5** [comment]
Hi no i have not deleted it.
I tried your link and it wanted to use my alexa app. And still did not work. So i downloaded the alexa app again on my tablet and all seens to work, not sure why. But thank you for your help.

Andyuk

On 2 May 2017 20:14, Ben Hardill <notifications@github.com> wrote:

@pckhib<https://github.com/pckhib> I'm guessing because I can't see the comment anymore on here you deleted it? If it redirected to a URL starting http://layla.amazon.com then it probably would have been an issue on the Amazon side of things.

@andyuk5<https://github.com/andyuk5> While I'm away I can't track down the issue you are seeing. Can you try and enable the skill by logging into here: http://alexa.amazon.co.uk/spa/index.html and see if you can authorise it from there

**Comment by hardillb** [comment]
The deleted comment was for @pckhib as I have a email with a comment, but it's not visible on the github website.

I meant to try the site on a desktop, but if it's all working now I'll close this out.

**Comment by andyuk5** [comment]
Hi
As of my last message I have my account linked to my Alexa, and Alexa has now found my device list which I setup on your site. But I still do not see my device List on the node red drop down.  Am I missing something. Sorry for being a pain and taking up your time.
Regards,

Andy

**Comment by hardillb** [comment]
Please start a new issue for that as it is very different problem.
