### ISSUE TITLE
Does not consistently convert to Fahrenheit <= 42 no conversion > 42 converts

### ISSUE THREAD

**Issue by ericl7577** [hardillb/node-red-alexa-home-skill-web#100]
I have tried this with a DS18B20 and a SI7021.  

Node-Red  5.0.6
node-red-contrib-alexa-home-skill 0.1.17

If I pass a value of 42 degrees or less Alexa has the same value in her response for the Pool Temperature (No conversion).  But, if I pass a value greater than 42 degrees she converts the value to Fahrenheit.  I tried setting my TH16 device to both Fahrenheit and Celsius but it makes no difference same results.  I can see the value is what I expect it to be in the msg.extra that is sent to the Alexa Home Response.  The conversion appears to take place in the Alexa Home Response.  Is this a bug?  Is there a setting that I am missing?

4/28/2020, 7:09:06 PMnode: c966be90.940b6
Temperature : msg.extra : Object
object
temperatureReading: object
value: 42
applianceResponseTimestamp: "2020-04-29T00:09:08.878Z"

Thanks!

**Comment by hardillb** [comment]
All the the conversion is done in Amazon's backend and nothing to do with this node/service.

As stated in the doc, all values should be passed in Centigrade only and no pool should be more 42 degrees Centigrade that is dangerously hot.

p.s. there is no Node-RED 5.0.6. The current latest version is 1.0.6

**Comment by ericl7577** [comment]
Thank you for the response.  My pool is not 42 Centigrade, but my attic may be this summer.  Did you happen to test this and get the same results?  It is fairly useless with this flaw.  Not your skill, the Alexa portion.
My Node-Red says "Node-Red 6.2.0 is available, You are currently running version 5.0.6"
Eric
    On Wednesday, April 29, 2020, 01:55:08 AM CDT, Ben Hardill <notifications@github.com> wrote:  
 
 


All the the conversion is done in Amazon's backend and nothing to do with this node/service.

As stated in the doc, all values should be passed in Centigrade only and no pool should be more 42 degrees Centigrade that is dangerously hot.

p.s. there is no Node-RED 5.0.6. The current latest version is 1.0.6
