### ISSUE TITLE
Smart Lock - Unlock

### ISSUE THREAD

**Issue by tepebox** [hardillb/node-red-alexa-home-skill-web#101]
Hi,
this component is really cool... However I have one issue. I want to build a Smart Lock (Garage door opener) which I want to open and close and query its status (opened/closed). I have the hardware for it (based on Tasmota) and now I need an Alexa skill. I found everything I need here but unfortunately Alexa (the app) tells me (or better: in the app I see a text below the lock status) that opening/unlocking this Smart Lock isn't supported. I'm located in Germany so I have a German Alexa app on my phone. Any idea how I can make it running? Otherwise I'm thinking about that I only use the Smart Lock device to query the status and use another device for opening/closing (so i.e.: switch on/off). Not very intuitive but should serve the purpose...

**Comment by hardillb** [comment]
I'm sorry, where different features are available is purely under Amzons's control.

The skill supports locking/unlocking and querying lock status so if it says it doesn't work then it must be down to Amazon's choices. The only thing it doesn't support is the use of a password/pin to unlock.

**Comment by tepebox** [comment]
Ahh, the PIN might be the issue, I heard (no evidence) that in Germany it's mandatory...

Thanks for the instant feedback...


Thomas
________________________________
