### ISSUE TITLE
Open and Close feauture?

### ISSUE THREAD

**Issue by shevu** [hardillb/node-red-alexa-home-skill-web#104]
On page [LINK](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-modecontroller.html) I saw that there is an option to manage "open" and "close" commands. Is it possible to add them?

**Comment by hardillb** [comment]
No, Open/Close actions were added in later version of the Alexa Home Skill API and without totally rewriting this skill it is not possible to add them.
