### ISSUE TITLE
 Enabling Amazon Skill outside the US

### ISSUE THREAD

**Issue by pedromargarido** [hardillb/node-red-alexa-home-skill-web#107]
Hi,

First I need to say I'm sorry, I'm new on using github and sent this as a Pull Request, but I think here is the right place.

I'm using a brazilian Amazon account and, for this reason, I can't activate your skill. Is it possible for you to enable people like me to activate it? 

If for performing that you need help translating some text, just tell me what is needed to be done I'll be glad to help.

![image](https://user-images.githubusercontent.com/53160650/93670137-4f7b0e80-fa6f-11ea-88a4-dc8ff126a3c6.png)

**Comment by hardillb** [comment]
duplicate https://github.com/hardillb/node-red-contrib-alexa-home-skill/issues/79
