### ISSUE TITLE
Not authorized error

### ISSUE THREAD

**Issue by ricatelli** [hardillb/node-red-alexa-home-skill-web#108]
My device  shows as reconecting/disconected and the log shows this:

14 Oct 00:12:04 - [error] [alexa-home-conf:44617f3e.42011] Error: connect ECONNREFUSED 34.240.81.189:8883
14 Oct 00:12:15 - [error] [alexa-home-conf:44617f3e.42011] Error: Connection refused: Not authorized

What I doing wrong?

**Comment by hardillb** [comment]
You should ignore the `Error: connect ECONNREFUSED 34.240.81.189:8883` error as it is trying to connect to a fallback address.

As for `Error: Connection refused: Not authorized` this implies that you have entered the wrong password.

You should also make sure you only have a single `alexa-home-conf` configuration node listed under the Configuration nodes sidebar

**Comment by ricatelli** [comment]
Yes, I left a single configuration first and then re-entered the credentials. And everything is working fine.
Thanks a lot!
