### ISSUE TITLE
Must log onto AWS often

### ISSUE THREAD

**Issue by SteveRMann** [hardillb/node-red-alexa-home-skill-web#109]
Often, not always, when I do a redeploy in node Red, I am prompted in the debug messages to log on to my_ip:3456, where I have to log on to my Alexa account again.

The error texts are:
ENOENT: no such file or directory, open 'alexa.txt'
open 192.168.1.54:3456 in your browser
Error: connect ECONNREFUSED 34.240.81.189:8883

Is this normal?

**Comment by hardillb** [comment]
`Error: connect ECONNREFUSED 34.240.81.189:8883` is totally normal and can be ignored.

The other is nothing to do with my service/nodes.
