### ISSUE TITLE
Devices not in drop down

### ISSUE THREAD

**Issue by andyuk5** [hardillb/node-red-alexa-home-skill-web#11]
Hi
As of my last message I have my account linked to my Alexa, and Alexa has now found my device list which I setup on your site. But I still do not see my device List on the node red drop down. Am I missing something. Sorry for being a pain and taking up your time.
Regards,

Andy

**Comment by hardillb** [comment]
Wrong repo, please open against the node repo (https://github.com/hardillb/node-red-contrib-alexa-home-skill) so it's tracked properly.

Also include detailed steps about how reached the problem, e.g. drag node on to canvas, add new connection details...
