### ISSUE TITLE
Device of type curtain

### ISSUE THREAD

**Issue by vdiogo** [hardillb/node-red-alexa-home-skill-web#111]
How could I create a new device of the type curtain: up + down + stop?

**Comment by hardillb** [comment]
That device type and traits are not supported at the version of the Alexa Smart Home API this skill uses

**Comment by vdiogo** [comment]
Thank you for prompt reply. 
So I'm guessing I can create two entities: one of the type on/ off for up/ down and another one of the type on for stop?

**Comment by hardillb** [comment]
Yes you can give that a try
