### ISSUE TITLE
Connection-Error

### ISSUE THREAD

**Issue by Highfiverico** [hardillb/node-red-alexa-home-skill-web#112]
the Error „Error: read ECONNRESET“ repeats itself over and over again followed by the error „Error: connect ECONNREFUSED 34.240.81.189:8883“.
but Internetconnection works very Fine
Version: 0.1.18
Node-red Version: 1.0.5

**Comment by hardillb** [comment]
Ignore it, the node will reconnect on port 1883 after about 10 seconds.

**Comment by hardillb** [comment]
If you are seeing a constant connect/disconnect loop then you have more than one instance signed in with the same id. This will NOT work, you can only have one instance in use.

It may be that you have multiple config nodes in a single Node-RED instance, you should only have one shared between all the device nodes.
