### ISSUE TITLE
thermostat > howTo

### ISSUE THREAD

**Issue by novitibo** [hardillb/node-red-alexa-home-skill-web#114]
hi.
could you please guide me to configure node-red flow for using Home assistant thermostat?
I would like that Alexa can increase/decrease temperature and turn/off thermostat.
If I create application type as thermostat and connect it my home assistant thermostat in node-red, new device appears in Alexa app devices tab, but it doesn't change the temperature...

Please help.

Tnx!

**Comment by hardillb** [comment]
Sorry, I don't use Home Assistant so I can't help with that.

I would expect you are going to need something between the Alexa-in node and the Home Assistant node to convert the input messages into something Home Assistant understands

**Comment by hardillb** [comment]
I suggest you ask on the Home Assistant fourms
