### ISSUE TITLE
Delete Account

### ISSUE THREAD

**Issue by EspElement** [hardillb/node-red-alexa-home-skill-web#117]
I am trying to delete my account on the site, but I can only find how to add devices or log out. Thoughts? Thanks!

I am troubleshooting things on my end and want to remove the account to confirm them. Thanks!

**Comment by hardillb** [comment]
Th option for users to delete accounts isn't present at the moment.

You should be able to unlink the service from the Alexa App that will remove all devices from your Amazon account.

If you still want to delete the account let me know your username and I'll remove it from the DB

**Comment by EspElement** [comment]
I have it disconnected from Alexa (I think) but it still seems to be adding the items. For now, can you remove EspElement from the database please? Thank you very much!!!

**Comment by EspElement** [comment]
Thank you, so you know, after deletion I am still getting the issue, I didnt think this was it for sure, but something seemed strange. Now just struggling to find it. 

Thanks!
