### ISSUE TITLE
Possibility to add Blinds

### ISSUE THREAD

**Issue by Martin-FFB** [hardillb/node-red-alexa-home-skill-web#118]
Hi,
Thank you for your really nice solution. Works like a charm...
Unfortunatly, currently there is no device for Blinds... i use the lock device, but it works not perfektly for blinds...

is there any posibility to add this type of device or is there already a work-a-round?

Thank you
Martin

**Comment by hardillb** [comment]
No, Blinds were added at a later version of the Amazon Smart home spec and it would require a full ground up rewrite of the service to add them, which I just don't have time to do.

You can use lights with the brightness control, with on/off being fully open/closed and brightness % being partial open. But you need to talk to it as if it's a light which is not natural.

**Comment by Martin-FFB** [comment]
Thank you for your reply... i currently use switch command and it works because the Blinds are just have a up/and a down switch. No need for %, but the main issue is to use "on" and "off" for open and close... is there no simple way to just add a 2th kind of switch that supports up and down instead of on/off? 
thank you
Martin

**Comment by hardillb** [comment]
No, all the voice processing is done by Amazon. As I said the only way to get support for Blinds is to rewrite the entire service. This is not going to happen
