### ISSUE TITLE
Lights Turning Off after 1 Hour

### ISSUE THREAD

**Issue by MylesGreater** [hardillb/node-red-alexa-home-skill-web#119]
Hi, 

I'm using this skill bridge to detect the Device "Bedroom Lights" in node red, which then passes to turn on phillips hue bulbs connected via mosquito and Zigbee2Mqtt but for some reason after an hour they just turn off again. 

Is this an issue with the bridge or?? 

Thanks

**Comment by hardillb** [comment]
No, this will be nothing to do with the service. It only sends commands when it receives them from the Alexa system.

Quickest way to test will be to attach a debug node to the device input node.
