### ISSUE TITLE
Home Response on thermostat

### ISSUE THREAD

**Issue by maragelis** [hardillb/node-red-alexa-home-skill-web#12]
Can you please help on an issue i have, I am trying to get the set temp from a thermostat. 

I am getting an error from alexa saying Thermostat is not responding. 
Below are the two Json REQUEST and RESPONSE

REQUEST
{ topic: 'Thermostat',
 name: 'Thermostat',
 _messageId: '95384156-4614-4ef6-b4c7-07ed573a28de',
_applianceId: '1486',
_confId: '36ceff97.eb119',
command: 'GetTargetTemperatureRequest',
extraInfo: {},
 _msgid: '123db99b.e49ce6' }

and the RESPONSE i am sending 

{ topic: 'Thermostat',
name: 'Thermostat',
_messageId: '95384156-4614-4ef6-b4c7-07ed573a28de',
_applianceId: '1486',
_confId: '36ceff97.eb119',
command: 'GetTargetTemperatureRequest',
extraInfo: {},
_msgid: '123db99b.e49ce6',
extra: { targetTemperature: { value: '19.0' } },
payload: true }

any help will be appreciated

**Comment by hardillb** [comment]
I've just fixed something but you need to add a bit to the `extra` in the response:

```
msg.extra = {
    "targetTemperature": {
        "value": 22.20
    },
    "applianceResponseTimestamp": new Date().toISOString(),
    "temperatureMode": {
        "value": "AUTO"
    }
};
msg.payload = true;

return msg;
```

The temperatureMode value can be "AUTO", "HEAT", "COOL", "CUSTOM"

If you use "CUSTOM" you have to include a `friendlyName` value:

```
 "temperatureMode": {
        "value": "AUTO",
        "friendlyName": "Some description"
    }
```

**Comment by hardillb** [comment]
See here for more details of values for the extra field: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/smart-home-skill-api-reference#getTargetTemperatureResponse

extra maps to payload in the Alexa docs

**Comment by maragelis** [comment]
thanks that did the job. The link above was excellent
