### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by INDRANI125** [hardillb/node-red-alexa-home-skill-web#120]
My device is continously connecting & disconnecting despite of having net connection "Error: read ECONNRESET" coming.skill is enabled & it was working fine previously

**Comment by hardillb** [comment]
You can only have ONE instance of the config node that has to be shared between all device nodes. Check you only have one config node by picking "Configuration nodes" from the menu in the top right.

You can also only use the skill with one instance of Node-RED at a time.

**Comment by INDRANI125** [comment]
Yes..it was logged in from two devices inside nodered.
