### ISSUE TITLE
You are not eligible to enable this skill due to geographical restrictions. 

### ISSUE THREAD

**Issue by rodrifo6** [hardillb/node-red-alexa-home-skill-web#121]
Hello.

I was implementing a flow with this skill and when it got to the part of getting the skill enabling I got the message in the title.
Granted, I live in Brazil and, although I use mainly english on my Alexa devices, it seems Amazon doesn't like it.

Is there any way I can help add language support for Brazilian Portuguese on this skill?

**Comment by hardillb** [comment]
duplicate https://github.com/hardillb/node-red-contrib-alexa-home-skill/issues/79
