### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Stuke00** [hardillb/node-red-alexa-home-skill-web#123]
Node-RED Alexa Smart Home Skill Bridge

It looks like the skill is currently experiencing a problem at the moment. Give it a couple of minutes and if it's still a problem please check if there is an existing open issue on GitHub here, if not then raise one.

**Comment by SteveRMann** [comment]
Still down

**Comment by smnino** [comment]
Same... maybe it's finally dead. Knew this day was coming....

**Comment by fpovoski** [comment]
Still down

**Comment by mrbridge** [comment]
also still down

**Comment by dibyadip-das** [comment]
Still down

**Comment by mtoensing** [comment]
Still down

**Comment by Bra1nK** [comment]
Same here, not working

**Comment by CaptainSweatpants** [comment]
Still Down 6hrs

**Comment by hardillb** [comment]
back up

**Comment by SteveRMann** [comment]
Thanks for providing a great service. Curious, what was wrong?

**Comment by fpovoski** [comment]
Thanks Ben, sending you a coffee
