### ISSUE TITLE
Password Change Link

### ISSUE THREAD

**Issue by tomlyo** [hardillb/node-red-alexa-home-skill-web#125]
I'm attempting to change the password using the Lost Password [link](https://alexa-node-red.bm.hardill.me.uk/lostPassword) and the email to change it never shows up. (Yes I've checked the junk folder, waited a considerable amount of time, and attempted resetting multiple times). Email is Gmail.

**Comment by hardillb** [comment]
I need to know the username for the service and email address you entered to look it up.

**Comment by TomLyon** [comment]
> I need to know the username for the service and email address you entered to look it up.

Emailed it to you. This account was set up today if that makes any difference. I just want to provide a more secure password than the one I set it up with.

**Comment by TomLyon** [comment]
Working now. Thanks.
