### ISSUE TITLE
alexa app doesn't show device state with auto ack

### ISSUE THREAD

**Issue by smcgann99** [hardillb/node-red-alexa-home-skill-web#127]
Hi,

In alexa pc app for example the state is grey - its not on or off

I tried just sending payload true to response node, but should there be something in msg.extra ?

eg for a light / switch etc do I need to send the actual state somehow ?

**Comment by hardillb** [comment]
If auto acknowledge is enabled you should not be using the response node at all.

The service does not support changing the status outside of a response to a command and the following section from the docs is important:

>  Messages passed to this (response) node need to have orginated from a Alexa Home node

**Comment by smcgann99** [comment]
Just to clarify please -

If I ask Alexa to turn off a light, there is no way to feed back the state so it shows as off in alexa app ?

**Comment by hardillb** [comment]
As I said, when auto acknowledge is enabled (which is what you asked) you should not be using the response node at all. All commands will be assumed to have succeeded.

If auto acknowledge is not checked, then you must use a response node, the message that arrives at the response node **must** be the same message that left the device node. For lights the **only** thing you change is set `msg.payload` to true or false. And that should reflect of the command succeded or failed.

If any of the nodes between the device node and the response node replace the `msg` object then none of this week work

**Comment by smcgann99** [comment]
I guess I'm not making myself clear -

Alexa responds OK with auto ack or if I send true via response node, but the state of device shown in alexa app doesn't show the actual device state. So from app I cannot tell if a device is on or not. I'm asking if this is possible.

**Comment by hardillb** [comment]
Device state was not included in the version of the API the skill is written against, if Amazon are not keep track based on command acknowledgement then no there is no way to update in the phone app.

**Comment by smcgann99** [comment]
OK thanks for your help
