### ISSUE TITLE
alexa-home node keeps reconnecting

### ISSUE THREAD

**Issue by iLem0n** [hardillb/node-red-alexa-home-skill-web#13]
Hello, 

i have an issue with the alexa-home node. 
I have a node-red instance running on a raspberry pi zero w with a simple example flow. 

The alexa-home node connects successfully but after about 5 seconds it disconnects and reconnects again. 
because of this endless loop it sometimes works and somtimes not.

I didnt find something usefull on my own.

Could you help me find a solution for that ?

**Comment by hardillb** [comment]
Sounds like you are trying to sign in from 2 different instances of node-red at the same time.

This is not possible, you can only have one instance connected at once, if you have 2 they will keep kicking each other off. If you only have one, make sure you only have 1 instance of the config node with the credentials in and out is shared with all the device nodes.

If you post your username I can check the logs, but not until tomorrow

**Comment by iLem0n** [comment]
Sometimes its so easy ;) 
I had another pi running which i tested earlier. After deleting the node from the second one it works like a charm.

Thank for your quick help
