### ISSUE TITLE
Skill stopped working

### ISSUE THREAD

**Issue by arvage** [hardillb/node-red-alexa-home-skill-web#130]
Hello hardillb,
thank you for your amazing skill. it's been years that I'm using it without any hiccups. Today I notices that my Alexa couldn't talk to my devices so I started troubleshooting and ended up disabling the skill and reenable to re-link but Alexa/Amazon couldn't do the authorization anymore and I can't link my account anymore.
Could you please look into this issue. it's probably an auth problem.

Thank yo
![Screenshot 2021-12-07 104915](https://user-images.githubusercontent.com/21295839/145088561-172b83a3-a5fa-4dd7-9bdc-ef856a3fa3e9.jpg)
![Screenshot 2021-12-07 104924](https://user-images.githubusercontent.com/21295839/145088563-1f362012-6087-4148-846b-88873b2fc828.jpg)
u

**Comment by NorthernMan54** [comment]
FYI - Amazon is currently having issues

https://downdetector.ca/status/amazon-alexa/

**Comment by hardillb** [comment]
Closing as I assume everything is working again now us-east-1 is back up and nobody is screaming.
