### ISSUE TITLE
Smartlock

### ISSUE THREAD

**Issue by Ikswoknib** [hardillb/node-red-alexa-home-skill-web#132]
Hello,
I want to use the command open and close for my garage. So i added a new device and gave it the Action Lock/Unlock and the Type Smartlock. The Close command is working. But for open there comes the message that i have to edit the settingts of the lock to allow opening via alexa. But in the settings there is no button for that.
Even if i go to the device in the Alexa App, it tells me the device does not answer.

any suggestions?

**Comment by hardillb** [comment]
The version of the API the skill is based on does not support the advanced lock features
