### ISSUE TITLE
Connection Refused - Not Authorized

### ISSUE THREAD

**Issue by Agratam** [hardillb/node-red-alexa-home-skill-web#133]
I have some issue this morning, Nodered nodes cannot connect and I have this error in the log.
"Error: Connection refused: Not authorized"
I can log to the web site, although i bumped into a momentary error there.

Is it only me? Is there some maintenance ongoing?

Thanks

**Comment by hardillb** [comment]
Yes there is.

**Comment by hardillb** [comment]
OK, should be back on old hardware while I work out what was wrong on the new.

**Comment by Bra1nK** [comment]
Yep working again
