### ISSUE TITLE
SmartLock response stopped working

### ISSUE THREAD

**Issue by ikohlernz** [hardillb/node-red-alexa-home-skill-web#134]
Hi there,

First of all, thanks for you hard work to make this skill available.  In last month or so, I have noticed that the response to smartlock stopped working.

This is my flow :
![image](https://user-images.githubusercontent.com/60406185/149649125-ab6789d0-62b5-44b6-a69a-ed9e20a7bd1f.png)

The function node has the basic setup:

msg.extra = {
    lockState: "UNLOCKED"
};
msg.payload = true;
return msg;

Node-red running as container in HA : v10.3.2
Username for your skill: ikohler.

I tried to re-linked my account I have tried to add new device "Underground" , but same result. 
I do not get any response from Alexa. I do have other devices temperate sensor and they still work find if I ask "What is the temperature in xyz".
I just wanted to check see if anyone has the issue or is it possibly due to the new API. 

Thanks

**Comment by hardillb** [comment]
Nothing has changed in the skill (or will) but it appears that Amazon are ignoring the response to a `GetLockStateRequest`.

This is something that has changed on Amazon's side and there is nothing I can do about it.
