### ISSUE TITLE
Skill bridge is not accessible

### ISSUE THREAD

**Issue by exKAjFASH** [hardillb/node-red-alexa-home-skill-web#139]
Hello.
For past 2+ hours https://alexa-node-red.bm.hardill.me.uk/ is showing "It looks like the skill is currently experiencing a problem at the moment". Can someone check why? In HA/NodeRed it also can't populate items. Thank you.

**Comment by Bra1nK** [comment]
I can confirm the skill doesn't appear to be working at the moment

**Comment by parabag** [comment]
I comfirm, the skill said: "It looks like the skill is currently experiencing a problem at the moment. Give it a couple of minutes and if it's still a problem please check if t[here](https://github.com/hardillb/node-red-alexa-home-skill-web/issues) is an existing open issue on GitHub here, if not then raise one." Anyone can help?

**Comment by freeantz** [comment]
not sure this can help, however until about 20 minutes ago alexa talked about a problem with the device (always working fine otherwise) while now it says OK but nothing happens. nodered is up but no traffic is reported whatsoever, neither before nor now

**Comment by freeantz** [comment]
life saver! I was afraid I had to switch off the lights through tapping on the phone, like a caveman! Or via the switches. Or via command line. Or.. hahahaha thank you!

**Comment by parabag** [comment]
yesssss... now is working...
