### ISSUE TITLE
Node not showing in palette

### ISSUE THREAD

**Issue by ins4neuk** [hardillb/node-red-alexa-home-skill-web#14]
Hi,

i try in install the nodes into red via the command line and also the palette way within node. it installs and shows it me in the "nodes.. filter nodes" sectionbut gives me greyed out boxes when i look at the palette and doesn't appear on the list of the nodes that i can use.

when i try to install this on the command line it gives me some warnings and then completes. when i then restart Red i get a syntax 
[alexa] SyntaxError: Unexpected reserved word
then it loads fine but there is no option to add/enables the sett up with the node red layout page.

and advice would be great

**Comment by ins4neuk** [comment]
![capture](https://cloud.githubusercontent.com/assets/28991053/26515668/ea4d1338-4274-11e7-9e9c-fd41dbe3a9e9.PNG)

**Comment by hardillb** [comment]
What version of NodeJS are you using to run what version of Node-RED?

**Comment by ins4neuk** [comment]
25 May 00:06:31 - [info] Node-RED version: v0.15.3
25 May 00:06:31 - [info] Node.js  version: v0.10.29

i'm quite new to this thou so not really sure what i'm doing to be honest

**Comment by ins4neuk** [comment]
also just noticed i may be posting on the wrong section lol told you i was new to this!! it was the other one i was trying to install node-red-contrib-alexa-home-skill should i post the question on that one!!!

**Comment by hardillb** [comment]
yeah, this should be against the node, but don't move it now.

I'm struggling to find somewhere to test a v0.10.29 of Nodejs. The node was built and tested on v4.x and v6.x.

Given 0.10.29 is out totally out of support is there any chance you can upgrade? I'm guessing you are on a raspberry pi, if so you can upgrade with the `update-nodejs-and-nodered` script that ships with node-red. It should bump you up to v6.x and Node-RED 16.3

**Comment by ins4neuk** [comment]
just doing it now and will let you know. i looked into upgrading not long ago did what i thought and broke node-red so thought it wasn't up gradable or there was some weird and wonderful way of doing it... never knew there was a simple script lol.

once this is done i'll feed back and let you know how i got on.  thanks again for your help

**Comment by ins4neuk** [comment]
BOOOOOOM.

all up and running mate. set up one called chair and one called test as on and off and both giving a Boolean response of true or false depending on what i say.

cant thank you enough i learnt 2 things today.. how to get your node to work and how to upgrade my node-red :D
