### ISSUE TITLE
Server not responding

### ISSUE THREAD

**Issue by mondedos** [hardillb/node-red-alexa-home-skill-web#144]
Hello.

From nodered I connect perfectly to my account
node-red-alexa-home-skill-web and from Alexa I can sync the devices. However, when I try to interact from Alexa to turn a device on or off, Alexa displays the following message "Waiting for Node-Red".

Then it shows the following message: "server not responding"

Is it a bug? What I can do?

Thanks in advance and greetings.

**Comment by hardillb** [comment]
Without more information I can't answer this.

Are you using auto response?

**Comment by mondedos** [comment]
Thanks, now it's working fine.
