### ISSUE TITLE
"Upgrade" in Home Assistant kills Alexa Home

### ISSUE THREAD

**Issue by SteveRMann** [hardillb/node-red-alexa-home-skill-web#146]
Reference: https://github.com/hassio-addons/addon-node-red/releases

The upgrade to Version 12.0.2 in Home Assistant deleted Alexa Home nodes.  Are you aware of this?

![Missing Nodes](https://user-images.githubusercontent.com/8091425/172759920-e059e6a6-dc64-413b-99e3-e4bfb1b6004f.jpg)

**Comment by hardillb** [comment]
Have you read the release notes, it explicitly says the nodes have been removed. Not sure what you expect me to do about this?

**Comment by SteveRMann** [comment]
I had auto-update turned on and didn't even know there was an update until after everything stopped working.

**Comment by hardillb** [comment]
But that's between you and HomeAssistant, not this skill.

Auto enabling updates that have major version number changes is always going to break things.
