### ISSUE TITLE
How to change from heat to cooling

### ISSUE THREAD

**Issue by NovaGL** [hardillb/node-red-alexa-home-skill-web#15]
Amazing work you have done.

I can turn on and of my aircon and set temperature.

But how do I adjust the fan or change from heating to cooling.

What is the right phrase to say and how would I do that in Node-red

**Comment by hardillb** [comment]
Just use the no/off and percentage actions, you may need to create some new "devices" e.g.

 - a "heat" and "cooling" device with on/off action
 - a "fan" device with on/off and percentage

**Comment by NovaGL** [comment]
I'm confused. You closed this too soon.

Can I do on a thermostat set heat to 20.

I can't do percentages as it's a thermostat

**Comment by hardillb** [comment]
As I said, create new additional devices for heat/cooling and the fan that you can turn on/off or set the percentage. Amazons device profiles won't let you mix and match all capabilities so you if you want that much control you will need multiple devices with separate names
