### ISSUE TITLE
Alexa do not find devices

### ISSUE THREAD

**Issue by juessi** [hardillb/node-red-alexa-home-skill-web#156]
Hi,
the node red skill is activated in alxa on the page ( https://alexa-node-red.bm.hardill.me.uk/devices) i have created a switch  the alexa home node in note-red is installed and me logged in. The switch is found in note-red but not by alexa
what can be the problem.
I look forward to a message
best regards Manfred

**Comment by hardillb** [comment]
This will be a problem on the Amazon side, best suggestion is to unlink the skill and relink it as there is nothing I can do help.
