### ISSUE TITLE
Reconnecting Problem

### ISSUE THREAD

**Issue by LostiLama** [hardillb/node-red-alexa-home-skill-web#158]
Hello, Yesterday my library just decided to turn on a permanent reconnect. Then I reinstalled the library and it all worked for about 1 minute. After that I always have to restart it so that it works for a minute again and again and again what can I do and what is the cause
![reconnecting](https://user-images.githubusercontent.com/86017905/235321367-a1238534-b7d9-4d8d-8f93-89bca6ebcf67.png)

**Comment by hardillb** [comment]
If it's reconnecting in a loop then you most likely have more than one instance running (or multiple config nodes in the same instance). You can only have 1 instance active.

Make sure you delete all but one alexa-conf nodes and only have 1 instance of Node-RED running.

**Comment by LostiLama** [comment]
![image](https://user-images.githubusercontent.com/86017905/235321522-fbb4ec47-84ca-42bd-b553-363061595d3d.png)
Thats all I have and it worked fine 2 days ago

**Comment by hardillb** [comment]
Any other running Node-RED instances? 

If not what do the Node-RED console logs show?

**Comment by LostiLama** [comment]
only 1 instance running here is what I got out the consol 
![Bild_2023-04-29_215629744](https://user-images.githubusercontent.com/86017905/235321790-4140096d-a196-4bc9-8009-33baf90d6d86.png)
