### ISSUE TITLE
Trying to query a HA entity but getting "sorry thats not supported yet"

### ISSUE THREAD

**Issue by daknightuk** [hardillb/node-red-alexa-home-skill-web#159]
Home assistant entity is called **sensor.battery_state_of_charge** this is a percentage from 0%-100%
I created this nodered flow which I think is correct but I don't know what to set up the entity on the skills bridge (or the exact phrase to ask alexa) I'm just looking to get a response from something like:

Alexa tell me the battery state

"Your battery is at xx percent" as a response.
I have read all the documentation and I have also posted in the nodered group for at least a couple of months and got no-where with it. I know this will be something simple, might not even be supported? hence why I raised this issue in the hope that either you can point me in the right direction or that an enhancement can be made to support this.

`[{"id":"e9fc7c35.44ca4","type":"api-current-state","z":"de7d428686d4597d","name":"Get entity state","server":"e7c1f572.ea52d8","version":3,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","entity_id":"sensor.battery_state_of_charge","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"","propertyType":"msg","value":"","valueType":"entity"}],"for":0,"forType":"num","forUnits":"minutes","x":620,"y":200,"wires":[["b7fa0d45.4a4a"]]},{"id":"e7c1f572.ea52d8","type":"server","name":"Home Assistant","version":5,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":"30","areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":"at: ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"h23","statusTimeFormat":"h:m","enableGlobalContextStore":true}]`

**Comment by hardillb** [comment]
This is not possible and there is no ongoing development for this skill (it is based on an old API that cannot support this)

**Comment by daknightuk** [comment]
Thanks I am working around this by just creating a switch in the skills bridge which will change the state of a HA entity, when that entity changes I will use the Alexa Media Player to report the entity value instead.

**Comment by Bra1nK** [comment]
VSH (Virtual Smart Home) can do this (and more)
