### ISSUE TITLE
temperatureMode CUSTOM doesn't respond correctly

### ISSUE THREAD

**Issue by NovaGL** [hardillb/node-red-alexa-home-skill-web#16]
Wondering if you can help.

If I do this in the payload Alexa responds settings undefined to 22

"temperatureMode":{
                    "value":"OFF"
                }

I also cannot get "AUTO" to respond correctly either. HEAT and COOL respond as expected

**Comment by hardillb** [comment]
OFF appears to be a new mode that wasn't present when I wrote this section of the node. I'll see if I can fix it, but it may be some time

**Comment by NovaGL** [comment]
Thanks what about AUTO?

**Comment by hardillb** [comment]
Show the whole message you are sending to the response node

**Comment by NovaGL** [comment]
Tried things like this. Tried with value AUTO and no friendly name which didn't work correctly.
If you do custom it is completly ignored.

If you do auto, the word auto is replaced with the room name. So alexa goes can't set room name room name to 18. Trying 18
```
	msg.extra = {
    "targetTemperature": {
        "value": 18
    },
    "applianceResponseTimestamp": new Date().toISOString(),
    "temperatureMode": {
        "value": "CUSTOM",
        "friendlyName": "FAN"
    }
};
msg.payload = true;

return msg;
```

**Comment by hardillb** [comment]
The following works for me

```
msg.extra = {
    "targetTemperature": {
        "value": 22.20
    },
    "applianceResponseTimestamp": new Date().toISOString(),
    "temperatureMode": {
        "value": "CUSTOM",
        "friendlyName": "Space Heater"
    }
};
msg.payload = true;
```

**Comment by NovaGL** [comment]
It's ignored for me.

So are you saying Alexa responds with "My Room Space heater set to 22"?

With HEAT I get "My Room HEAT set to 22"?
With AUTO I get "My Room set to 22"?

On a positive note. The OFF command now works. She replies "My Room is OFF"

**Comment by hardillb** [comment]
I'm saying that for a device called "thermostat" if I ask "Alexa what is the thermostat set to" I get back "The space heater is set to 22.2"

**Comment by NovaGL** [comment]
Strange I can't get it to work. It says it's not responding

**Comment by NovaGL** [comment]
Figured it out. Some commands don't allow the use of friendly name.

Eg GetTargetTemperatureRequest does but GetTemperatureReadingRequest doesn't

**Comment by hardillb** [comment]
Ahh, yes. It only really makes sense when asking what the device is set to, not what the current temperature is.

**Comment by NovaGL** [comment]
I just call the skill my room. But want it to reply with the name not saying my room. Not a big deal.

The Alexa names can be confusing for what they do. Thanks. Hope you can add home entertainment soon
