### ISSUE TITLE
Connect/Disconnect Loop

### ISSUE THREAD

**Issue by rschwarzjr** [hardillb/node-red-alexa-home-skill-web#160]
node-red-contrib-alexa-home-skill node flips back and forth between connected and disconnected approximately every 4 seconds. 

Deleted and rebuilt node but still sees the same issue. Login seems to work as device populates correctly. Before deleting and adding node this was an old install that was working fine for a few years then something changed, possibly on my end.

**Comment by hardillb** [comment]
Duplicate https://github.com/hardillb/node-red-alexa-home-skill-web/issues/158

**Comment by Bra1nK** [comment]
This can happen if you've more than one instance connected. You can only have one logged in.

On 21 August 2023 12:56:59 BST, rschwarzjr ***@***.***> wrote:
>node-red-contrib-alexa-home-skill node flips back and forth between connected and disconnected approximately every 4 seconds. 
>
>Deleted and rebuilt node but still sees the same issue. Login seems to work as device populates correctly. Before deleting and adding node this was an old install that was working fine for a few years then something changed, possibly on my end. 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/hardillb/node-red-alexa-home-skill-web/issues/160
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Samsung S9 Plus with K9 Mail

**Comment by rschwarzjr** [comment]
I saw that in an older issue. Only have the node used once and only one install but I will check again. Thanks.

Robert Schwarz
***@***.******@***.***>


From: Brian Kelly ***@***.***>
Date: Monday, August 21, 2023 at 7:59 AM
To: hardillb/node-red-alexa-home-skill-web ***@***.***>
Cc: Robert Schwarz ***@***.***>, Author ***@***.***>
Subject: Re: [hardillb/node-red-alexa-home-skill-web] Connect/Disconnect Loop (Issue #160)
This can happen if you've more than one instance connected. You can only have one logged in.

On 21 August 2023 12:56:59 BST, rschwarzjr ***@***.***> wrote:
>node-red-contrib-alexa-home-skill node flips back and forth between connected and disconnected approximately every 4 seconds.
>
>Deleted and rebuilt node but still sees the same issue. Login seems to work as device populates correctly. Before deleting and adding node this was an old install that was working fine for a few years then something changed, possibly on my end.
>
>--
>Reply to this email directly or view it on GitHub:
>https://github.com/hardillb/node-red-alexa-home-skill-web/issues/160
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
--
Sent from my Samsung S9 Plus with K9 Mail
