### ISSUE TITLE
connect - disconnect loop - not a duplicate of issue #158.

### ISSUE THREAD

**Issue by glover-glitch** [hardillb/node-red-alexa-home-skill-web#161]
I have the same issue of a random 'out of the blue' loop occurring.
This service has been rock solid for years.

My issue seems to be the same as #158 however, I've confirmed the following;

I only have 1 instance of node-red running listening on port 1880.
![image](https://github.com/hardillb/node-red-alexa-home-skill-web/assets/73205151/636e43a8-a7a7-464d-95af-7846e84f42cf)

I only have one instance of the Global Configuration Node.
![image](https://github.com/hardillb/node-red-alexa-home-skill-web/assets/73205151/8152bf1c-8243-4fd7-a6ad-1c6ba00375e7)

And I only have 3 flows that use this.
![image](https://github.com/hardillb/node-red-alexa-home-skill-web/assets/73205151/d8103d4a-5a0f-4c2f-a85a-ca264fd8b23f)

Is there anything else that I can check for?

As an aside, I noticed that I stopped sending monthly beers because github stopped using paypal.
I apologize.  This is a great service that I regularly use.

**Comment by hardillb** [comment]
The only way to get a connected/disconnected loop is to have more than one instance trying to connect.

Are you 100% sure there isn't another Node-RED instance running on another machine somewhere?

What is the time interval between the connect/disconnect?

And what is your username so I can check the broker logs?

**Comment by hardillb** [comment]
Assuming `sendspamhere` is the username, here is the logs from the broker

```
1696784280: Client sendspamhere already connected, closing old connection
```

So there is 110% 2 instances running somewhere

**Comment by glover-glitch** [comment]
My username is sendspamhere.

I apologize.
I misunderstood the multiple instances problem.
I thought it was for a single machine.
I did in fact setup a second rpi running node-red recently for a different project.
Thus, I do have two different machines each running nodered and this service.
That would do it.

I may be able to work around this by having all instances on one machine then use mqqt to broker messages to the second machine.  But that seems like a clunky work around.
Could I resolve this by having multiple accounts on your service attached to a single Alexa skill?

**Comment by hardillb** [comment]
I don't think so, I do not believe Amazon will let you sign up to a skill twice (at least not with the same Amazon id)

**Comment by glover-glitch** [comment]
ok, well thank you.

I very much appreciate your prompt replies.  Thank you.
And again, I apologize for my oversight.
