### ISSUE TITLE
To set a percentage below 36% doesn't work on Alexa

### ISSUE THREAD

**Issue by christianbalz** [hardillb/node-red-alexa-home-skill-web#163]
I am adding a new device designed to control the opening of a curtain. It offers the ability to perform various actions, such as opening, closing, stopping, and adjusting to a specific percentage. When I ask Alexa to set the curtain to 50%, everything works smoothly. However, I've noticed that if the percentage is equal to or below 35%, Alexa mentions the name of another device, and upon checking the logs in Node Red, for instance, there is no record of any action taking place.

`10/01/2024, 13:01:54[node: debug 1](http://192.168.15.95:1880/#)
msg.payload : number
36`

![image-01](https://github.com/hardillb/node-red-alexa-home-skill-web/assets/26635391/56253ccf-920c-4a1a-9053-66e8dd6a13fc)

**Comment by hardillb** [comment]
The skill doesn't set any limits on what % can be requested, any strange behaviour like that is all going to be on Amazon's side of things.

**Comment by hardillb** [comment]
A quick test with a light I have here is working with 5%

**Comment by christianbalz** [comment]
I removed the device from all locations, created a new one, and asked Alexa to recognize it again. I conducted a new test, and everything is working now. I don't have an explanation for this. Nonetheless, thank you very much for the support

**Comment by christianbalz** [comment]
Subsequently, I conducted a new test by asking Alexa to 'stop' the curtain while it was opening, and it seems that she initiates a reversal of the command when asked to stop. Regarding the skill, is there any intention to create an option for this, specifically related to the 'stop' command?

**Comment by hardillb** [comment]
The skill is based on a now obsolete version Amazon's smart home skill api, there is no way to add any new device types or actions without re-writing the whole thing from scratch which I do not have the time to do (and I mainly use Google Home devices at home now).

The skill is effectively in maintenance mode.

**Comment by Bra1nK** [comment]
Try node-red-contrib-virtual-smart-home which was last updated 5 days ago and has more features

**Comment by christianbalz** [comment]
That's unfortunate; many people use the service you created, and it will become obsolete over time. Anyway, thank you again
