### ISSUE TITLE
tre device

### ISSUE THREAD

**Issue by andrea-ap** [hardillb/node-red-alexa-home-skill-web#165]
I inserted 3 devices, they work, if I insert the 4th, it disconnects me, and the other 3 disconnect and reconnect

**Comment by hardillb** [comment]
You are going to need to supply a LOT more detail here.

But the usual reason for disconnect loops is that you have more than one client connected. This can be any of the following:

1. More than one instance of Node-RED using the same account
2. More than one config node using the same account. All devices **MUST** share the same config node

None of these will work.

**Comment by andrea-ap** [comment]
> You are going to need to supply a LOT more detail here.
> 
> But the usual reason for disconnect loops is that you have more than one client connected. This can be any of the following:
> 
> 1. More than one instance of Node-RED using the same account
> 2. More than one config node using the same account. All devices **MUST** share the same config node
> 
> You can **ONLY** have 1 instance of the account connected.

Ok, now solve, many thanks .
