### ISSUE TITLE
Request / Question: Support for Blinds / Covers / Rollershutters in Home-Assistant

### ISSUE THREAD

**Issue by TomMarg** [hardillb/node-red-alexa-home-skill-web#166]
Hi - would it also be possible to add blinds / covers / rollershutters as supported devices since they would require up/down/stop as command sets?
I used this in OpenHAB but currently I am migrating to HA with just this detail missing which was supported there.

Besides that: Great work!!

**Comment by hardillb** [comment]
https://github.com/hardillb/node-red-alexa-home-skill-web/issues/118
