### ISSUE TITLE
Inquiry Regarding Integration of Roller Shutters

### ISSUE THREAD

**Issue by Dabert89** [hardillb/node-red-alexa-home-skill-web#168]
I would like to politely inquire whether it might be possible in the future to set up a roller shutter as a device. 

I would like to control my KNX roller shutters via voice command. 

I have already integrated all the lights and it works wonderfully. 

Thank you for any development.

**Comment by hardillb** [comment]
Duplicate https://github.com/hardillb/node-red-alexa-home-skill-web/issues/166
