### ISSUE TITLE
GetTemperatureReadingRequest

### ISSUE THREAD

**Issue by 1rvy** [hardillb/node-red-alexa-home-skill-web#17]
First off, many thanks for this great piece of work!

Having a play with your Node-Red skill for Alexa integration, this is much simpler than enabling Alexa discovery on all my ESP8266 nodes as now I can use MQTT and have Node-Red bridge between AVS and MQTT - perfect!
I have basic on/off control from Alexa through your skill to an ESP8266 controller, so I am happy the Skill is integrated with Node-Red correctly.
I am struggling to get current temperature from another ESP8266 based temperature sensor, feature wise this is now reportedly working on AVS here in the UK.
Can you give me a bit of guidance to how I get a MQTT reported temperature topic value to respond to the GetTemperatureReadingRequest?

**Comment by hardillb** [comment]
Which regions different capabilities are available in are entirely down to Amazon not me unfortunately. They tend to release new capabilities in the US first then open them up to the UK next, before Germany.

It looks like my doc is now a little behind the Amazon doc (https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/smart-home-skill-api-reference#temperature-control-and-query-messages) and that capability should be now available in the UK.

As for using it, I suggest you keep the latest value from the sensor in the flow context and use this value to create a response message to reply to the request.
