### ISSUE TITLE
Unregister my account

### ISSUE THREAD

**Issue by Snubbeke** [hardillb/node-red-alexa-home-skill-web#184]
How to unregister my account?

**Comment by hardillb** [comment]
If you mean delete your account, please supply your username and the registered email address and I will delete it.

If you don't want to post them here you can email them to me at `hardillb @ gmail .com`

**Comment by Snubbeke** [comment]
Username = Snubbeke with this email address.
Thank you for all the good work!
Regards,
Peter

**Comment by hardillb** [comment]
Done

**Comment by Snubbeke** [comment]
Awesome, thanks for the update!

Op wo 18 dec 2024 21:55 schreef Ben Hardill ***@***.***>:
