### ISSUE TITLE
Node-RED Skill

### ISSUE THREAD

**Issue by 8art-5imson** [hardillb/node-red-alexa-home-skill-web#2]
Hi
I cant find the Node-Red skill in skills on Amazon. is this USA only?
Thanks Chris

**Comment by hardillb** [comment]
The skill is still under review by Amazon so until that finishes the skill is only available to those on the beta test team. I will email all signed up users once Amazon have finished (4 weeks and counting)

**Comment by hardillb** [comment]
The skill is now live in the US, UK and Germany if you want to have a play
