### ISSUE TITLE
Devices gone offline

### ISSUE THREAD

**Issue by antsman** [hardillb/node-red-alexa-home-skill-web#20]
Hi, today got devices not responding to Alexa.  In Alexa app they are also offline.

Timewise it matches what you said to guevara777 about expiring Oauth tokens as I started using your (great) service/skill about 3 months ago, around March 24.

Also tried disabling the skill, then enabling it again with account linking.  Stays same .. new and old devices are not discovered :(

Cheers, Aivo

**Comment by hardillb** [comment]
Can you share your userid so I can test a quick fix please

**Comment by antsman** [comment]
Sure, username is "aivo".

**Comment by hardillb** [comment]
OK, I've reset the expiry on your token to 2117, can you try it now please

**Comment by antsman** [comment]
Online again and responding!  Many thanks, really quick fix ;)

**Comment by hardillb** [comment]
Now to mess with EVERYBODIES record in the db and not break everything....
