### ISSUE TITLE
Package won't install. 

### ISSUE THREAD

**Issue by marksmanaz** [hardillb/node-red-alexa-home-skill-web#21]
From the .node-red directory in the pi home directory I tried:

npm install node-red-contrib-alexa-home-skill
sudo npm install node-red-contrib-alexa-home-skill
npm install -g node-red-contrib-alexa-home-skill
sudo  npm install -g node-red-contrib-alexa-home-skill

None work no nodes show up.

I did try installing from the pallet manager and the nodes showed up for only a moment and then disappear. Not sure whats going on.

Thanks,

Mark

**Comment by hardillb** [comment]
If you've run all of those then we have a lot of cleaning up to do.

Did you restart node-red after running any of those commands? As stated in the linked to Node-RED documentation, when you install Node-RED modules from  the command line with npm you have to restart Node-RED for it to pick up the modules.

First lets clean up, from `/home/pi/.node-red` run the following:

    sudo npm uninstsall node-red-contrib-alexa-home-skill
    sudo npm uninstall -g node-red-contrib-alexa-home-skill

That should have removed both the global and the local copy, you can check they are gone by  looking in both the `/home/pi/.node-red/node_modules` and `/usr/lib/node_modeules` directories. There should be no directory called `node-red-contrib-alexa-home-skill` in either now.

Now we've cleaned up lets try and work out what is happening. Before trying to install the node again some questions to get a baseline:

 - How did you install Node-RED? 
 - How are you running Node-RED, as a service or from the command line?
 - Do you know where the logs are kept and how to view them?

**Comment by marksmanaz** [comment]
Yes I ran both these uninstall commands:

> sudo npm uninstsall node-red-contrib-alexa-home-skill
> sudo npm uninstall -g node-red-contrib-alexa-home-skil

There is no directory called  node-red-contrib-alexa-home-skill in these directories:

> /home/pi/.node-red/node_modules and /usr/lib/node_modeules

Node-red was installed on the rpi when I got it. I entered "sudo systemctl enable nodered.service" on the command line to have it run as service.

I am sure npm and node-red have logs I do not know where they are.

**Comment by hardillb** [comment]
OK, so you are probably still on the back level 0.15.x and well out of support nodejs 0.10.x.

Follow the upgrading instructions here to move you up to 0.16.x and the supported nodejs 6.x then use the pallet manager to reinstall the node.

For reference Node-RED on a Pi logs to the Syslog and you can use the command `node-red-log`

npm logs to the console where you run it.

**Comment by marksmanaz** [comment]
Was there supposed to be a link "here" to upgrade instructions?

**Comment by hardillb** [comment]
http://nodered.org/docs/hardware/raspberrypi#upgrading

**Comment by marksmanaz** [comment]
It is now all working perfectly. Thank you for your time and concern.
