### ISSUE TITLE
new smart home controls

### ISSUE THREAD

**Issue by NovaGL** [hardillb/node-red-alexa-home-skill-web#23]
Hi,

Wondering if you will be updating this to support the new smart home controls.

Would love TV and music control.

https://developer.amazon.com/blogs/alexa/post/78f44d51-5bdf-4a4c-8eaa-57d1282c8212/introducing-entertainment-capabilities-in-alexa-smart-home-new-device-controls-for-tvs-av-receivers-and-ir-hubs

**Comment by hardillb** [comment]
I'll have a look, but I've not had much time recently. It looks like there is a new version of the message format so I'll have to make sure that doesn't break anything as well.

**Comment by antsman** [comment]
Feels unstable from amazon for now ..
https://forums.developer.amazon.com/questions/79788/smarthome-entertainment-problem-with-alexaspeaker.html

**Comment by scobby** [comment]
any progress here?

**Comment by hardillb** [comment]
No, a complete rewrite to support v3 of the API will be needed and I'll probably build a dual Alexa/Google home service at some point but I just don't have time at the moment

**Comment by coldfire84** [comment]
I've forked this repo and updated to Smart Home API [v3 skill](https://nr-alexav3.cb-net.co.uk/), if you are interested in testing let me know.

**Comment by hardillb** [comment]
No need to cross post to all the repos.

Please do not publish this to the NPM just yet, we should discuss how we keep just 1 version of the node prevent fragmenting and confusing end users.

**Comment by djim1** [comment]
Is it possible to add functions for controlling blinds/cover/garage door in Home assistant,
[https://www.home-assistant.io/components/cover.mqtt/](url)
Now I can use 'open', 'close' with the TurnOnRequest (open) and TurnOffRequest (close) . I don't know how to use the 'stop' commands with the alexa home node for controlling the blinds to stop at a certain point?
I rather want to use new commands to controle 'open', 'close' and 'stop', is this possible to at to the commands?

**Comment by hardillb** [comment]
No, not at the moment, the skill is based on the V2 API which doesn't support open/close/stop

**Comment by djim1** [comment]
> No, not at the moment, the skill is based on the V2 API which doesn't support open/close/stop

wil it be in the (near) future?
