### ISSUE TITLE
Feature Request: Multiple choice

### ISSUE THREAD

**Issue by Shogun1978** [hardillb/node-red-alexa-home-skill-web#24]
It would be nice to give not just on and off commands but also concrete requests. I use the node-red to control my tv and Yamaha AVR. I would be cool to e.g. choose the input like "Alexa, switch Yamaha to net radio". In best case choose the station.

**Comment by hardillb** [comment]
Smart home skills can only implement commands in for the list here: 

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/smart-home-skill-api-reference

There is a new set of commands recently released that I will look at when I get time that include some support for AV equipment: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/building-smart-home-skills-for-entertainment-devices

A request to support this has already been raised in #23

**Comment by scobby** [comment]
any progress? would be interessted to

**Comment by hardillb** [comment]
Don't SPAM all the issues
