### ISSUE TITLE
Unable to select a Device

### ISSUE THREAD

**Issue by hendrikbrandhoff** [hardillb/node-red-alexa-home-skill-web#25]
![grafik](https://user-images.githubusercontent.com/19148405/28501799-d435556e-6fe3-11e7-9bc5-b8b5ce728efe.png)

Hey! :-)

I am trying to connect my Node-Red-Flow with the Echo-Dot following your installation guide and documentation on your product website. I am currently not able to select a previously added device in the Alexa-Home-Node (see attached screenshot). 
Still refreshing, reboot and re-installation doesn't work for me. 

Is there an issue with the way I tried to do so or may there be any different issue?

Thanks in advance for your help. 
Regards. Hendrik.

**Comment by hardillb** [comment]
First guess is you've got the password wrong when you added the account to Node-RED.

Is there anything in the Node-RED logs, especially when you hit the refresh button?

**Comment by hendrikbrandhoff** [comment]
Thx for your fast reply offering your help. It was caused by an old Nodered-Version. So I upgraded and now works fine!

**Comment by hendrikbrandhoff** [comment]
Thx for your fast reply offering your help. It was caused by an old Nodered-Version. So I upgraded and now works fine!
