### ISSUE TITLE
IMPORTANT - HTTPS Certificate invalid. Nothing is working

### ISSUE THREAD

**Issue by Crypti-x** [hardillb/node-red-alexa-home-skill-web#26]
See: https://alexa-node-red.bm.hardill.me.uk/

**Comment by hardillb** [comment]
Bugger I was sure that was next week. I'm away from home at the moment will
fix as soon as I get home tomorrow

**Comment by Crypti-x** [comment]
Great! Ps: How I can donate? c:

**Comment by solariz** [comment]
I have good experience with the [acme.sh](https://github.com/Neilpang/acme.sh) LE Script, works like a charm by cronjob.

**Comment by hardillb** [comment]
It doesn't work on bluemix, I have a workaround, it just requires manually
uploading the certs to the console. It will get done early afternoon
tomorrow.

**Comment by hardillb** [comment]
Certificate should be updated, all should be working again now.

**Comment by Crypti-x** [comment]
Yeee, nice!
