### ISSUE TITLE
"Error: Connection refused: Not authorized"

### ISSUE THREAD

**Issue by chno299** [hardillb/node-red-alexa-home-skill-web#27]
Hi, I have successfull setup my account here; 
https://alexa-node-red.bm.hardill.me.uk/

Also i linked the skill to alexe, and she find the device i added...

also i can import alexa devices in my node red dashboard, but at this time i got every few seconds,
this error message: "Error: Connection refused: Not authorized"

i tried to use another account, new devices and so so on...
my firewall is open

![image](https://user-images.githubusercontent.com/10000613/31046016-65e458a0-a5f1-11e7-858f-227a36ab8885.png)

**Comment by hardillb** [comment]
I'll have a look at the logs, but double check there are no trailing spaces on the end of the username or password you entered in the account config.

Also when exactly did you create the account?

**Comment by hardillb** [comment]
username/passwords are also case sensitive

Also check what IP address alexa-node-red.hardill.me.uk (note no 'bm' in the middle) resolves to

**Comment by chno299** [comment]
Hello Ben,

First: Thanks for your Time!

the username (chno299) must be correct, because node red dashboard shows me
immediately my device after i entered my credentials..

The ip for :alexa-node-red.hardill.me.uk is:

34.253.184.44

Best Regards from Austria




*Mit freundlichen Grüßen*


Mobil:0664 432 86 93
Web:netztech <http://netztech.at/>.at

Kristallstrasse 18
A-4407 STEYR-GLEINK
Österreich

DVR: 0999466
UID: ATU24149106

2017-09-30 15:12 GMT+02:00 Ben Hardill <notifications@github.com>:

**Comment by hardillb** [comment]
When did you create the account?

**Comment by chno299** [comment]
not sure, i think bevore 3 days...
i also make a new account "mulder299" (yesterday)
this also not works...


btw: my ip is: 90.152.129.171



*Mit freundlichen Grüßen*


Mobil:0664 432 86 93
Web:netztech <http://netztech.at/>.at

Kristallstrasse 18
A-4407 STEYR-GLEINK
Österreich

DVR: 0999466
UID: ATU24149106

2017-09-30 16:45 GMT+02:00 Ben Hardill <notifications@github.com>:

**Comment by hardillb** [comment]
mulder299 is not in the database, which implies you managed to created while I was moving the system to it's new back end.

**Comment by chno299** [comment]
i tried to register now:

[image: Inline-Bild 1]

*Mit freundlichen Grüßen*


Mobil:0664 432 86 93
Web:netztech <http://netztech.at/>.at

Kristallstrasse 18
A-4407 STEYR-GLEINK
Österreich

DVR: 0999466
UID: ATU24149106

2017-09-30 18:31 GMT+02:00 Ben Hardill <notifications@github.com>:

**Comment by hardillb** [comment]
OK, thanks, you've just helped me notice the web frontend was still pointing at the old database. Everything should be pointing at the new database now (where there should be no mulder299).

Did you try changing the password on either of the chno299 account at some point?

Can you try and log into the web with chno299 now I've fixed the DB

**Comment by chno299** [comment]
OK - i am connected now!

Thanks for the Ultrafast Fix

**Comment by hardillb** [comment]
So the chno299 account is working now or did you add a new mulder299 account?

**Comment by chno299** [comment]
i add the mulder299 account.

*Mit freundlichen Grüßen*


Mobil:0664 432 86 93
Web:netztech <http://netztech.at/>.at

Kristallstrasse 18
A-4407 STEYR-GLEINK
Österreich

DVR: 0999466
UID: ATU24149106

2017-09-30 20:08 GMT+02:00 Ben Hardill <notifications@github.com>:
