### ISSUE TITLE
Devices not responding

### ISSUE THREAD

**Issue by davesidious** [hardillb/node-red-alexa-home-skill-web#28]
Hi

Sometime in the last 48 hours all my devices have stopped responding.  I've ruled out everything but your service - is there something weird with my account ('daverr')?

Cheers!
Dave

**Comment by JonAld** [comment]
I had the same yesterday afternoon. Reboot of node red seemed to solve it

Jon

**Comment by hardillb** [comment]
The service migrated backend on Friday and there was a small mix up with which database the frontend was pointing at between then and yesterday.

If you created devices in that period please check they are still showing in the web front end as some may  have ended up only in the old DB.

Also as @JonAld said it may help to restart Node-RED as there was a DNS update as well so a restart should ensure everything points to the new stuff.

**Comment by davesidious** [comment]
Perfect - a restart of my node-red container did the trick - all my devices are working correctly.  Thanks for the prompt response, @JonAld and @hardillb!
