### ISSUE TITLE
Device not responding

### ISSUE THREAD

**Issue by wildwiz** [hardillb/node-red-alexa-home-skill-web#29]
Hi, since past Friday Alexa rejects my commands with device not responding. I already tried to remove and rediscover the devices, they are all discovered fine but sending commands to them fails as descripted. Maybe a certificates issue between Alexa and the service your side ? Thank you in advance !

**Comment by hardillb** [comment]
This is down to me migrating the backend to a new host. Restart Node-RED
and it should reconnect to the new host

**Comment by wildwiz** [comment]
Cool, man !
Thank you for your prompt reply, it solved.

For others having this problem, the issue was not about the device not executing the commands, but about alexa rejecting them with a voice error. That is why I considered it different from issue #28.

I really appreciate both your work and your helpfulness, Ben ! 
Thumbs up for you and thanks again!
