### ISSUE TITLE
Cannot Login and switching Devices

### ISSUE THREAD

**Issue by Crypti-x** [hardillb/node-red-alexa-home-skill-web#30]
Browser Timeout by clicking to Login Button. Node-Red is "reconnecting"

**Comment by hardillb** [comment]
This is because AWS wiped out the DB and the broker. I'm working on it, but it may be tomorrow morning by the time I get it fixed

See this other issue: https://github.com/hardillb/node-red-contrib-alexa-home-skill/issues/23

**Comment by Crypti-x** [comment]
Ok, thx ^^

**Comment by hardillb** [comment]
Temp fix in place, but any new accounts or device changes since Sept 29th have been lost. 

If you need to recreate your account, remove and re-add the skill to Alexa and do discovery again.

If it's just devices ask alexa to discover devices to pick up any changes.

**Comment by Crypti-x** [comment]
Ok, thanks.
