### ISSUE TITLE
Disconnecting always

### ISSUE THREAD

**Issue by chichiberti** [hardillb/node-red-alexa-home-skill-web#31]
My alexa home node in node-red disconnects alll the time. Is there a solution?

Thanks

**Comment by hardillb** [comment]
Make sure you have restarted node-red

If it's still a problem then most likely you have 2 clients trying to connect at once, you can only have 1.

This might be 2 copies of the config node so check that by clicking on the menu in the top right and select "Configuration nodes"

**Comment by chichiberti** [comment]
Thats it! I had two Clients connecting. Problem solved!
Thanks.
