### ISSUE TITLE
Update to Smart Home API V3

### ISSUE THREAD

**Issue by NovaGL** [hardillb/node-red-alexa-home-skill-web#32]
Amazon is changing the way Alexa acts with Smart Home skills, meaning the payloads will have different information in them.

Are you considering moving to this new API?

https://developer.amazon.com/blogs/alexa/post/87c5cf67-1f27-42d3-a07a-e4f559674392/how-to-migrate-your-alexa-skill-to-the-updated-smart-home-skill-api

**Comment by hardillb** [comment]
Probably at some point, but as usual no promises as to when

**Comment by scobby** [comment]
Would be great if this will be done. With V3 we can extract the source of the command. I have a Alexa Dots in every room and want to know where the "lights off" command came from.

**Comment by hardillb** [comment]
You can already do that by creating room groups and add the devices in the rooms. Just set the Appliance type on the devce

**Comment by hardillb** [comment]
Also the V3 API does not identify which Alexa device the request came from. That information is NOT in any of the Home Skill API levels (and it shouldn't be)

**Comment by scobby** [comment]
i think you mean the "Group" function on alexa.amazon.com. That doesnt work for me.
I have a dot called "Wohnzimmer" (living room) and just tried to create a group "Wohnzimmer". 
Alexa tells me, thats not possible, the group "Wohnzimmer" already exists.

**Comment by hardillb** [comment]
I have a dot called bedroom and a group called bedroom and it works fine, but all that is on the Amazon side, nothing to do with the skill

**Comment by LuckyStyle** [comment]
> You can already do that by creating room groups and add the devices in the rooms. Just set the Appliance type on the device

Can you explain how to do this? I would like to know which echo dot was used for the request. I have created two different groups and added my device to each group. But I dont see anything in node-red that is different to tell me which echo was used. Thanks.

**Comment by NovaGL** [comment]
Node red doesnt know. You can only do the setup in the alexa app. Additional information is not available

**Comment by LuckyStyle** [comment]
Gotcha. Thanks.
