### ISSUE TITLE
NOTHING is working anymore...

### ISSUE THREAD

**Issue by Crypti-x** [hardillb/node-red-alexa-home-skill-web#33]
https://alexa-node-red.bm.hardill.me.uk/ not working - nginx Error. I cannot switch lights too.

**Comment by hardillb** [comment]
As an error report this is next to useless

**Comment by hardillb** [comment]
Please include a lot more details when you report errors (to any project), just saying everything is broken doesn't help anybody.

I have restarted the process, it should be working again now.
