### ISSUE TITLE
Skill is unresponsive

### ISSUE THREAD

**Issue by kdubovenko** [hardillb/node-red-alexa-home-skill-web#34]
Hello, first of all, thank you for an awesome tool. I have been using it for a few months now without issues. In that last few days it stopped working completely. i am getting a "Sorry, the device xxx is not responding" message from Alexa. I am also unable to discover new devices so looks like communication between Alexa and the servers is down. I tried resetting alexa, adding / removing devices from your website, changing node-red settings but no solution so far. Any ideas how I can bring it back to life? Thanks!

**Comment by kdubovenko** [comment]
I created a test account and was able to create new device and have it be discovered by Alexa... Still trying to see how I can get my old account back online

**Comment by hardillb** [comment]
This is probably because your oauth token has expired (after 3 months), I can't get Alexa to renew tokens properly, like it's supposed to.

I can fix the token expiry manually (set it to 100 years), but not until I get home tonight.

**Comment by kdubovenko** [comment]
Thank you for a quick response, that makes sense. If needed, my account ID for your website is the same as here. Appreciate the help!

**Comment by hardillb** [comment]
OK, the account for the username kdubovenko the token is already set to expire in 2117 so it's not that, but the date matches.

Did you try re-linking original account in the alexa app?

**Comment by kdubovenko** [comment]
That's 100 years of automation! Sounds like a good time :). I did re-ling yesterday, through the alexa app by disabling and re-enabling the skill. The only thing that worked was to create a "test" account instead (kdubovenko_test). I'll give it another shot with the original account tonight, just in case. I'll post the result here.

**Comment by kdubovenko** [comment]
Tried re-linking the original account again but the issue persists, looks like I'll be switching to the secondary account I created for now. If I am able to come up with a solution myself, I'll post it here.
