### ISSUE TITLE
fahrenheit?

### ISSUE THREAD

**Issue by dahlheim2** [hardillb/node-red-alexa-home-skill-web#36]
i've got the Node-RED Alexa Home Skill Bridge working :)

however, i would like to change the units used by the thermostat functions from Celcius to Fahrenheit.  could you point me in the right direction? 

Thanks!

**Comment by hardillb** [comment]
You can set the `temperatureReading.scale` field in the response to either CELSIUS or 
FAHRENHEIT

**Comment by dahlheim2** [comment]
cool!  thanks.  how does that apply to the msg.payload=false (failure) response?

    On Monday, December 11, 2017, 8:42:48 AM MST, Ben Hardill <notifications@github.com> wrote:  
 
 
You can set the temperatureReading.scale field in the response to either CELSIUS or
FAHRENHEIT

**Comment by hardillb** [comment]
It doesn't make sense for a failure as the temperatures are not reported iirc

**Comment by hardillb** [comment]
If you mean the range response (for out of range values) these have to be in Celsius

**Comment by dahlheim2** [comment]
sorry, would you happen to know what to ask the Echo to query a thermostat's setpoint?  it always responds with the temperature reading...  :-/

    On Monday, December 11, 2017, 11:31:37 AM MST, Ben Hardill <notifications@github.com> wrote:  
 
 
If you mean the range response (for out of range values) these have to be in Celsius

**Comment by hardillb** [comment]
The [doc](https://alexa-node-red.bm.hardill.me.uk/docs#buildFlows) covers both, for GetTemperatureReading and GetTargetTemperature.

Or do you mean how to actually ask Alexa as in what words to say?

**Comment by hardillb** [comment]
Closing this due to no response
