### ISSUE TITLE
node red forgets the alexa skill - what to do?

### ISSUE THREAD

**Issue by bikeadventure** [hardillb/node-red-alexa-home-skill-web#37]
Hi,

I managed to install the palette in node red (v0.15.3) but it does not really work.
First I cannot chose the devices I added on your bridge page after having registered with my credentials. I tried with two accounts, both fail.
![bildschirmfoto 2017-12-11 um 22 47 32](https://user-images.githubusercontent.com/34459902/33858655-c964d9f0-ded0-11e7-8b2e-daac093d96df.JPG)

After reloading the node red programming web page the newly installed palette is forgotten,
I receive an error message: "Imported unrecognised types:  alexa-home, alexa-home-conf".
The alexa home node and its connection to the next node are dotted lines then.
![bildschirmfoto 2017-12-11 um 22 12 10](https://user-images.githubusercontent.com/34459902/33858669-ceae2b6e-ded0-11e7-92b5-be7300f25a9f.JPG)

I tried this several times on two different raspberries.

What is wrong?

Regards

Peter

**Comment by hardillb** [comment]
I seam to remember seeing this with either that version of Node-RED or a back level version of NodeJS.

Please upgrade Node-RED to 17.x and probably make sure you are on at least Node 6.x (anything else it very out of support these days).

If you still have a problem after that, then please supply node-red logs and check the browser console for any errors

**Comment by bikeadventure** [comment]
Dumb me, updating to recent node red version 0.17.5 did the trick. Thanks a lot!
