### ISSUE TITLE
ColorTemperatureRequest

### ISSUE THREAD

**Issue by fholler0371** [hardillb/node-red-alexa-home-skill-web#39]
Requesttype DecrementColorTemperatureRequest/IncrementColorTemperatureRequest come with a alexa answer "device not responed", but i can see the request in the debug. What kind of responde i need.

**Comment by fholler0371** [comment]
All other works fine

**Comment by hardillb** [comment]
Look in the Amazon docs [here](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/archive/shv2-smart-home-skill-api-reference#tunable-lighting-control-messages) for some pointers. I'll try and add an example to the docs later

**Comment by fholler0371** [comment]
Thanks for your help!

**Comment by hardillb** [comment]
See example in #46
