### ISSUE TITLE
Custom Home Skill Configuration

### ISSUE THREAD

**Issue by waynehaffenden** [hardillb/node-red-alexa-home-skill-web#4]
I appreciate that you are waiting for the skill to be verified by Amazon but in the meantime I was interested in hosting this myself for personal use.

I've hopefully setup all the various components required but am unsure of the configuration needed for the Alexa Home Skill portal? I've made some guesses but it's not working. The main problem I have right now is that I've set the Authorization URL to https://blah/login which does open the login screen to this web app on the Alexa app for "account linking" but logging in does not satisfy what the account linking procedure requires? I'm guessing there is a different URL or query string required for this?

Can you confirm and also advise me on any other settings or things you feel I might need to get this working please. If you have any documentation you could point me to this would also be great.

Thank you

**Comment by hardillb** [comment]
Unfortunately it's not that simple, you need to generate OAuth tokens, store them in the database and then add them to Lambda console.

I suggest you read up on OAuth and then look at the routes that start /auth.

The whole stack really wasn't designed to be run for single users, you really will do better waiting for Amazon to approve it.

**Comment by waynehaffenden** [comment]
Fixed it.

**Comment by hardillb** [comment]
The skill has gone live now if you want to switch over to the "official" version
