### ISSUE TITLE
Cannot distinguish between set, increase, decrease

### ISSUE THREAD

**Issue by rPraml** [hardillb/node-red-alexa-home-skill-web#40]
I've set up a device and checked `%`, `+%` and `-%`

But I cannot distunguish between these three. I got the messages below.
Is there a trick to check, if the message's origin was a "SetPercentageRequest" or "IncreasePercentageRequest"?

Cheers 
Roland

### voice commands and returned messages

Alexa, set XY to 2 percent:
```
msg.payload : number
2
```

Alexa, increase XY by 2 percent:
```
msg.payload : number
2
```

Alexa, decrease XY by 2 percent:
```
msg.payload : number
-2
```

**Comment by hardillb** [comment]
Look at the WHOLE message not just the payload in the debug node
