### ISSUE TITLE
English-AU Support

### ISSUE THREAD

**Issue by NovaGL** [hardillb/node-red-alexa-home-skill-web#43]
It is possible for you to add Australian support. It doesn't need any changes you just need to add the language and copy the information across.

**Comment by hardillb** [comment]
The skill has been submitted for certification in Austrialia

**Comment by NovaGL** [comment]
Any update on certification? Seems to be taking awhile

**Comment by hardillb** [comment]
The Japanese team keep bouncing it for some reason (it's already approved in Japan). I think I've fixed what they are moaning about so we'll just have  to see

**Comment by NovaGL** [comment]
Thanks. Can you post here when approved

**Comment by hardillb** [comment]
Done

**Comment by NovaGL** [comment]
Brilliant. Thanks :)

**Comment by NovaGL** [comment]
Doesn't work. Just says not responding. While the Echos set to English-US work.
