### ISSUE TITLE
Connection Problems

### ISSUE THREAD

**Issue by Uppermill** [hardillb/node-red-alexa-home-skill-web#44]
I am having intermittent connection problems and I cannot seem to make any progress on the issue. For the last two days it will not log onto the bridge site at all.

I can log on using the browser.

The node red skill lists the available devices.

Hep would be greatly appreciated.

Regards

Allan

**Comment by hardillb** [comment]
I need a lot more information

 1. What is your username on the system
 2. Does the node bounce between connected/reconnecting status or just stay in reconnecting mode?
3. Where in the world are you?

**Comment by stmiko** [comment]
Hi and first of all: Thanks for this service!

I got the same connection problem mentioned above.
If I change anything at the node-red flow (and deploy it), it takes up to 15 minutes until the "connected"-status is shown. It says "reconnecting" for this time.

I'm located in Germany, username stmiko.

Thanks in Advance.
Berst Regards,
Michael

**Comment by hardillb** [comment]
This should be now fixed (for now).

Please retest

**Comment by stmiko** [comment]
After some short test, its works quiet good. Thanks for your help!

Regards,
