### ISSUE TITLE
Support for DeviceID in Alexa Request

### ISSUE THREAD

**Issue by scobby** [hardillb/node-red-alexa-home-skill-web#47]
Can you support the DeviceID Tag?
So i can identify from which room (alexa deviceid) the request came.
So i can create a common device called "Light" and can switch light on/off for different rooms with the same command.

more information here: 
https://developer.amazon.com/de/docs/custom-skills/request-and-response-json-reference.html#request-body-syntax

**Comment by hardillb** [comment]
Device ID is not present in the Alexa Home Skill V2 api. The way to do this is to use room groups and to set the device type (just added) in the web page
