### ISSUE TITLE
"Connected" rotates around Alexa Home Nodes on flow

### ISSUE THREAD

**Issue by chrisbussey** [hardillb/node-red-alexa-home-skill-web#48]
I have created a very simple flow consisting of 3 Alexa Home nodes and 3 debugs.  They are all recognised by the Alexa skill.  When one connects the other two disconnect, then ~ 8secs later another one will connect but the currently connected one disconnects.  I cannot see how to have them all connected at the same time.

Any clues???
Thank you for the great work to date BTW.

Kind regards,

Chris Bussey

![screen shot 2018-02-17 at 15 45 37](https://user-images.githubusercontent.com/12814083/36342718-410ed8ee-13fa-11e8-9e67-ab8e036e57f9.png)
![screen shot 2018-02-17 at 15 45 29](https://user-images.githubusercontent.com/12814083/36342719-41370080-13fa-11e8-986d-f228868e7fdb.png)
![screen shot 2018-02-17 at 15 45 44](https://user-images.githubusercontent.com/12814083/36342720-415b8d4c-13fa-11e8-994d-6ee9f6b1ae73.png)

**Comment by hardillb** [comment]
How many config nodes do you have (how many times did you enter your username/password?) You should only have 1 shared between all 3 input nodes that way you only have 1 connection to the back end.

**Comment by hardillb** [comment]
You can view the configuration nodes by looking in the menu (top right burger)

**Comment by chrisbussey** [comment]
Thanks Ben, all sorted, sorry still a bit of a newbie with Alexa and Node Red.

Kind regards,

Chris Bussey
