### ISSUE TITLE
Cannot log-in to the website

### ISSUE THREAD

**Issue by wiatrM** [hardillb/node-red-alexa-home-skill-web#5]
Hello,

When I try to log-in with my username to https://alexa-node-red.bm.hardill.me.uk/ got the message that my password is incorrect. After a password reset- login is done automaticly- but after logout is the same situation - cant log-in again.

**Comment by hardillb** [comment]
What username?

**Comment by wiatrM** [comment]
Mwiatr

**Comment by hardillb** [comment]
ok, I've worked it out, there is a space on the end of your username that I didn't strip when you registered. I'll have to edit the DB to fix it (and push a change to the forms to trim spaces). I'll post back when I've fixed the DB

**Comment by hardillb** [comment]
OK, your login should be fixed now, I'll push the site update to stop it happening again later with a few more updates.
