### ISSUE TITLE
Login to https://alexa-node-red.bm.hardill.me.uk fails

### ISSUE THREAD

**Issue by detlefs** [hardillb/node-red-alexa-home-skill-web#50]
Hi there,

currently it's impossible to log in to the site. Also, Nodes can't connect.

There's an nginx error:

Something has triggered an error on your website. This is the default error page for nginx that is distributed with the Amazon Linux AMI. It is located at /usr/share/nginx/html/50x.html

You should customize this error page for your own site or edit the error_page directive in the nginx configuration file /etc/nginx/nginx.conf.

**Comment by hardillb** [comment]
fixed
