### ISSUE TITLE
Devices be show "offline" in alexa app.

### ISSUE THREAD

**Issue by ss301** [hardillb/node-red-alexa-home-skill-web#54]
Since yesterday, the devices be show "offline" in alexa app and not working. My device lang is japanese. Is there a solution?

**Comment by syaoyou** [comment]
Me too
Since yesterday, the devices be show "offline" in alexa app and not working. My device lang is japanese.

**Comment by hardillb** [comment]
When did you create your account and devices?

There was a AWS outage on Friday and as a result the database backing the system was lost, unfortunately the last backup available was from the 24th of February so any accounts/devices created after that time have been lost.

Please log into the website to check, if your username/password are not recognised then you will need to recreate your account and devices and then unlink/relink the skill in the Alexa app. 

If just your devices are missing then you can just recreate them and ask Alexa to discover devices again.

You will also need to log into node-red and reselect the devices in the drop down on each input node to make sure their UUIDs are updated.

Sorry for any inconvenience. 

I have improved the back up scripts so there is less likely hood of data being lost in the future.

**Comment by ss301** [comment]
I did what you said. I recreate the account, also devices and relink the skill. but devices are recognized.

**Comment by ss301** [comment]
I checked again, It's working perfectly.
thanks.

**Comment by hardillb** [comment]
I'm going to close this issue now. @syaoyou if you still have a problem we can re-open it later.
