### ISSUE TITLE
Alexa home node does not send a color value

### ISSUE THREAD

**Issue by mrohner** [hardillb/node-red-alexa-home-skill-web#56]
When saying: " kitchen top color green" I do not get any color value from the Alexa home node. 

{"topic":"","name":"kitchen top","_messageId":"1cf93ab5-6133-4048-be9f-2f88a2d3e162","_applianceId":"20384","_confId":"5384fc6f.dabba4","command":"SetColorRequest","extraInfo":{},"_msgid":"1959b098.94eeef"}

**Comment by hardillb** [comment]
Thanks, I'll try and have a look but it might be a little later in the week

**Comment by hardillb** [comment]
I've tested this on my end and it's working properly.

Can you check what version of the node-red-contrib-alexa-home node you have installed.

**Comment by mrohner** [comment]
I upgraded to newest version  of the node-red-contrib-alexa-home node. I works now perfectly.
Thank you
