### ISSUE TITLE
https://alexa-node-red.bm.hardill.me.uk down?

### ISSUE THREAD

**Issue by antsman** [hardillb/node-red-alexa-home-skill-web#59]
nginx / AMI error page shows.

https://alexa-node-red.eu-gb.mybluemix.net is up.
Which is right today btw - are they working in parallel?

**Comment by hardillb** [comment]
The system is all up and running again as of 20mins ago. All working correctly

**Comment by hardillb** [comment]
https://alexa-node-red.bm.hardill.me.uk is correct and up and running

The old bluemix site has not been used in well over a year and as IBM cancelled by login when I left I can't shut it down.

**Comment by hardillb** [comment]
If it's still linked to anywhere in the docs let me known and I'll remove it
