### ISSUE TITLE
AlexaHomeResponse has stopped talking to me!

### ISSUE THREAD

**Issue by maxwellhadley** [hardillb/node-red-alexa-home-skill-web#60]
Possibly a server-side issue. I have a couple of temperature sensors which were working fine yesterday. I was able to as "Alexa, what is the inside temperature?' and get an answer. Today I get nothing, just silence, not even the 'not responding' message. Debug shows the same correctly-populated message object being sent to the AlexaHomeResponse node as yesterday. The flow has been running continuously between times (albeit the computer went to sleep overnight).

**Comment by hardillb** [comment]
This looks like a bug on the Alexa side, because when I try my thermostat test device it responds to the set point query but not the current temperature.

It's strange because it's not reporting an error, alexa just doesn't respond

**Comment by NorthernMan54** [comment]
Can confirm the same behaviour, she is silent for temperature sensors but will let you know what your thermostat is set to.

Looking at my logs, my system had responded with the current temperature, but silence from Alexa.

**Comment by jpfy** [comment]
Unfortunately I am having the same problem with temp requests

**Comment by hardillb** [comment]
This is an Amazon problem, not a problem with this skill.

**Comment by hardillb** [comment]
Case 5077442161 has been raised with Amazon.

**Comment by NorthernMan54** [comment]
Tks Ben

**Comment by hardillb** [comment]
Alexa devs have acknowledged this as a problem on their end

**Comment by maxwellhadley** [comment]
Seems to be fixed now!
