### ISSUE TITLE
Can not link to my account in Alexa app

### ISSUE THREAD

**Issue by ss301** [hardillb/node-red-alexa-home-skill-web#63]
Hi,
The same problem the issue #62 is happening again in my house, Will you remove all tokens from my account?

**Comment by hardillb** [comment]
That's a little difficult if you don't tell me your username

**Comment by ss301** [comment]
I have three accounts, x9vdsvv887q, md9cd454d and mies9idl.

**Comment by takamickey** [comment]
me too.
username: taka.mickey

**Comment by takamickey** [comment]
Thank you.
i can link.

**Comment by ss301** [comment]
It's working perfectly.
thanks.
