### ISSUE TITLE
Error: connect ECONNREFUSED 34.240.81.189:8883 on Deploy

### ISSUE THREAD

**Issue by vincentnl** [hardillb/node-red-alexa-home-skill-web#65]
Really enjoy your work.

It is working just fine, only that it gives:
Error: connect ECONNREFUSED 34.240.81.189:8883
everytime I deploy.

The node that raises the error is alexa-home-conf, what I can tell is the configuration node.

On functionality it works just fine, so I suspect that it
1. needs to refresh some token, and does that after first fail 
2. it does multiple calls to the alexa api, and it encounters throttling.

So maybe a fraction of delay would work, or suppressing the token refresh error.

Hope that I was clear enough.
![capture](https://user-images.githubusercontent.com/4074007/43354129-7f41359c-9246-11e8-823d-aecce11923df.PNG)

**Comment by hardillb** [comment]
This is just the node trying one of the multiple addresses to the MQTT broker used by the system. It can be ignored
