### ISSUE TITLE
Reconnecting

### ISSUE THREAD

**Issue by mbio16** [hardillb/node-red-alexa-home-skill-web#67]
Hello,

I use your skill in node-red for a long time. I got a problem in my code and it is showing reconnecting. I know that I got account ok because I can log in on your website and even Alexa can see the devices. However my node-red server can not see the devices.

Thank you,
Martin

**Comment by hardillb** [comment]
If it is constantly reconnecting that means you have 2 instances running at once for that user id. You can only have one, this is by design to stop 2 instances trying to respond.

**Comment by homing1923** [comment]
Hi,

Here got similar issue, successful login on website and discover-able device in alexa but always reconnecting in node-red.
Then I try to reinstall the module and now the npm also pop up the similar error.
` getaddrinfo EAI_AGAIN`

> ![err](https://user-images.githubusercontent.com/34162216/46712098-f64eb180-cc81-11e8-8f6f-47907b8861d4.PNG)

I seems to be a connection problem.

**Comment by homing1923** [comment]
> @homing1923 that error has nothing to do with the node or skill, it means npm can not resolve one of npmjs.org's servers.

@hardillb Alright, i finally get the module after 1000s.

`added 128 packages in 1137.695s`

Here is the real one.
`Error: getaddrinfo EAI_AGAIN alexa-node-red.hardill.me.uk:8883` 

I made a brand new acct

> ![ttt](https://user-images.githubusercontent.com/34162216/46718610-4b98bc00-cc9e-11e8-86ad-83ab08e2b46b.PNG)

and made a new device, also discovered in the alexa app.

> ![svvv](https://user-images.githubusercontent.com/34162216/46718711-a500eb00-cc9e-11e8-8217-bd09495caf20.jpg)

 to exclude from this issue.

> If it is constantly reconnecting that means you have 2 instances running at once for that user id. You can only have one, this is by design to stop 2 instances trying to respond.

Still, I cannot find any device on the node properties.
> ![tttt](https://user-images.githubusercontent.com/34162216/46717542-e8595a80-cc9a-11e8-84a0-e712bc675d0f.PNG)

and the error keeps on popping up in the debug 
![erre](https://user-images.githubusercontent.com/34162216/46718780-d8dc1080-cc9e-11e8-854b-c1f48b9388b6.PNG)

So what would causing this issue?
thanks

**Comment by hardillb** [comment]
The port 8883 error is not a problem, it's just the node trying to use one of the fall back addresses, if you leave it 30 seconds it will connect on port 1883. Unfortunately there is no easy to suppress the error message

**Comment by hardillb** [comment]
Actually the EAI_AGAIN means you have a DNS problem, this is the same problem that was effecting npm, it sounds like your pi is having problems looking up addresses

**Comment by mbio16** [comment]
I only have one instance with my user ID. When I try configure account it does not find it because when I try to find device in node-red It can not find any.

**Comment by homing1923** [comment]
Finally, I found what I messed up.

> ![reas](https://user-images.githubusercontent.com/34162216/46776244-59514e80-cd3d-11e8-9e6f-f563de80bda1.PNG)

Now everything works fine, many thanks @hardillb
