### ISSUE TITLE
can't delete devices

### ISSUE THREAD

**Issue by djim1** [hardillb/node-red-alexa-home-skill-web#68]
the 'DELETE' button doen't work. How can I delete added devices?

**Comment by hardillb** [comment]
You are going to need to supply a LOT more information.

- What is your username
- What Browser are you using
- Are there any errors in the browsers console.log?
- Which device are you trying to delete.

**Comment by hardillb** [comment]
Also Please use the #alex channel in the Node-RED Slack to ask questions

**Comment by djim1** [comment]
SOLVED!!!

I used Chrome.
In the meantime I solved it by opening it in an other browser (edge) and there it was no problem to delete the device, I received a pop-up. 
I did not expect to receive a pop-up so I changed my pop-up settings in Chrome, and it worked.

sorry for bothering!!
