### ISSUE TITLE
Node name reverts back from device name to Alexa home on change of topic.

### ISSUE THREAD

**Issue by ukmoose** [hardillb/node-red-alexa-home-skill-web#7]
The title says it all.  

If you have deployed a node and then try to edit the topic name the node name displayed on the node on the canvas reverts back from the device name to the generic "alexa home".  

workaround is to reselect alternative device and then select initial device again.

**Comment by hardillb** [comment]
Bah, this all worked before I had to change it for you freaks on Macs...

I'll have a look.

**Comment by hardillb** [comment]
Try changing the oneditsave on on the alexa-home node to:

```
        oneditsave: function() {
             var n = $('#node-input-device option:selected').text();
            //console.log("selected name " + n);
            this.name = n;
            $('#node-input-name').val(n);
        },
```

**Comment by ukmoose** [comment]
yep editing the topic now maintains the node-name.   Ta very muchly!
