### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by MiguelESP89** [hardillb/node-red-alexa-home-skill-web#71]
Hey, 
I included this Skill in my NodeRed System but the device is not connected. 
Which ports used the skill?

Thank you
Miguel

**Comment by hardillb** [comment]
The node connects out to the service, you shouldn't need to open any ports.

Please describe in a lot more detail exactly what you are seeing.

**Comment by MiguelESP89** [comment]
I created device on the homepage. Then i created a flow in nodered with the device from the site. I discoverd devices in Alexa and the device were found. But the flow in nodered didnt react if I ask alexa to turn the device on. 
![bildschirmfoto 2018-12-17 um 13 53 15](https://user-images.githubusercontent.com/39128034/50088383-29be3700-0203-11e9-80fe-4d9abb1254b7.png)

**Comment by MiguelESP89** [comment]
I'm using a Raspberry Pi (OS: Stretch) 
The nodejs version ist v8.12.0

**Comment by hardillb** [comment]
I still need the logs from Node-RED to see what error messages it is putting out

**Comment by hardillb** [comment]
I can't help unless you supply the logs. I can re-open the issue if you have them
