### ISSUE TITLE
Welche Ports werden genutzt? 

### ISSUE THREAD

**Issue by MiguelESP89** [hardillb/node-red-alexa-home-skill-web#75]
Hallo, 
wir haben bei uns eine Firewall die alle Ports erstmal blockiert. 
Ich benötige die Ports, die genutzt werden damit ich diese Freigeben kann. 

Vielen Dank 
Gruß 
Miguel

**Comment by hardillb** [comment]
Sorry you are going to have to ask this in English

**Comment by MiguelESP89** [comment]
Sorry, 
we have in our network a firewall where all the ports are blocked. 
Which ports do you use for the alexa skill? 

Thank you. 
Miguel

**Comment by hardillb** [comment]
The node only makes outbound connections on port 1883 or 8883

**Comment by hardillb** [comment]
And HTTPS request s

**Comment by MiguelESP89** [comment]
Ok Thank you =) 
Have a nice day
