### ISSUE TITLE
[REQUEST] audio device feature

### ISSUE THREAD

**Issue by Keltere** [hardillb/node-red-alexa-home-skill-web#77]
Hi i wanted to know if it's possible to add some controls for audio devices like mute, channel selection and volume set (i can currently use the percentage set but it's not working if i don't say `set`, in italian `imposta`)

Don't know why i cannot say `amplifier 10%` instead of `set amplifier at 10%`

**Comment by hardillb** [comment]
Audio control is part of the v3 API and as such not available with this skill
