### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by nilavachowdhury** [hardillb/node-red-alexa-home-skill-web#79]
Application error when deployed to heroku!

**Comment by hardillb** [comment]
Well that is a absolutely useless issue

**Comment by nilavachowdhury** [comment]
neither won't it run locally, it won't run in aws either.

**Comment by hardillb** [comment]
Again, absolutely no useful information here.

**Comment by hardillb** [comment]
Just to be totally clear here. The code works perfectly fine if you set the environment up correctly.

You have supplied absolutely no useful information about what you have tried here, not even the stack trace presented when the crashes on startup, or the environment you are trying to run it in (version of nodejs/is version). So I have nothing to work with.

If you want people to help you then you have to make it easy for them.

There are no setup instructions for this code for a number of reasons:

 - first, there was no intention for other people to run this, there is no benefit to polluting the Alexa skill store with multiple copies of the same thing.
 - If you are not capable of giving the code a quick read and working out what environment it needs to run then you really shouldn't be trying to run it.
 - the code is presented here for people to read if doing something similar and as a place for people to raise bugs against the service.

**Comment by nilavachowdhury** [comment]
Sorry for providing such less info, i actually made a skill which utilises blynk api to control all blynk devices, here's my skill - [https://www.amazon.in/Nilava-Chowdhurys-Smart-Home/dp/B07N8SKQX7/ref=sr_1_1?s=digital-skills&ie=UTF8&qid=1549630880&sr=1-1&keywords=chowdhury](url) 

Its fully functional but the only issue is for discovery device response i am hardcoding the devices in the lambda code itself and so it lacks any web ui to add and manage devices, i love your work and i wanted to modify it to accept blynk auth token and virtual pin in add device page and then pass the response to alexa, obviously giving you all the credits.

The problems i faced in heroku was error 503 , and in local deployment i got throw error,
i am using nodejs v10.15.0 and npm version 6.4.1
