### ISSUE TITLE
Alexa Home configuration wont accept

### ISSUE THREAD

**Issue by wexican1** [hardillb/node-red-alexa-home-skill-web#8]
Hello, when creating the node-red configuration for alexa home node I've added in my username & password, then the devices are listed after a press of the refresh button, i've clicked Auto Acknowledge, added a optional topic but when I hit the "Done" button nothing happens, any ideas what I'm doing wrong or where the issue may be? Please see attached jpg

Thanks,

Tom
![alexa](https://cloud.githubusercontent.com/assets/7568985/24625635/964a77ae-18a7-11e7-9de3-40640d9cb9aa.JPG)

**Comment by hardillb** [comment]
- What version of the node are you running
- What version of Node-RED
- What browser are you using
- Is there anything in the browser javascript console?

**Comment by wexican1** [comment]
Hi Ben,

Please see below my answers to your questions.

Thanks

Tom

- What version of the node are you running,                  I'm using (V6.10.1)
- What version of Node-RED,                                  I'm using (V0.16.0) 
- What browser are you using,                                I'm using google chrome Version 57.0.2987.133
- Is there anything in the browser javascript console?       Yes there is, please see next lines below.

VM1008:1 Uncaught SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.handleDebugMessage (eval at <anonymous> (vendor.js:2), <anonymous>:234:28)
    at Array.handleDebugMessage (eval at <anonymous> (vendor.js:2), <anonymous>:128:27)
    at WebSocket.d.onmessage (red.min.js:16)
handleDebugMessage @ VM786:234
handleDebugMessage @ VM787:128
d.onmessage @ red.min.js:16
VM1009:1 Uncaught SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.handleDebugMessage (eval at <anonymous> (vendor.js:2), <anonymous>:234:28)
    at Array.handleDebugMessage (eval at <anonymous> (vendor.js:2), <anonymous>:128:27)
    at WebSocket.d.onmessage (red.min.js:16)
handleDebugMessage @ VM786:234
handleDebugMessage @ VM787:128
d.onmessage @ red.min.js:16
VM1010:1 Uncaught SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.handleDebugMessage (eval at <anonymous> (vendor.js:2), <anonymous>:234:28)
    at Array.handleDebugMessage (eval at <anonymous> (vendor.js:2), <anonymous>:128:27)
    at WebSocket.d.onmessage (red.min.js:16)
handleDebugMessage @ VM786:234
handleDebugMessage @ VM787:128
d.onmessage @ red.min.js:16
VM1011:1 Uncaught SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.handleDebugMessage (eval at <anonymous> (vendor.js:2), <anonymous>:234:28)
    at Array.handleDebugMessage (eval at <anonymous> (vendor.js:2), <anonymous>:128:27)
    at WebSocket.d.onmessage (red.min.js:16)




----- Original Message -----

**Comment by hardillb** [comment]
I meant what version of the Alexa node are you using?

**Comment by hardillb** [comment]
I'm not sure what that error is, but implies there is some problem with the Node-RED Editor communicating with the back end so there could be all number of things wrong.

I would recommend that you update Node-RED to v0.16.2

**Comment by wexican1** [comment]
I've updated to node-red V0.16.2 & still it will not accept when the done button is pressed.
I'm using Alexa node version 0.1.15 is this the correct version? 
I might try using a fresh install of raspbian & node-red & see what happens.

**Comment by wexican1** [comment]
I've tried it with a fresh install & it works, 👍 however I'm not sure what is the problem with the original setup I have. I'd prefer to not have to re-install all nodes I've added in my setup, is there any way to find out from the CLI or other way why the configuration won't accept? Thanks.

**Comment by hardillb** [comment]
All of the validation is browser side so it would be have to be something in the browser console, but the errors you posted don't point to anything obvious.

I would suggest installing and configuring the other nodes one at a time if possible to see if it's an interaction with one of those that causes the problem.
