### ISSUE TITLE
ECONNREFUSED 34.240.81.189:8883

### ISSUE THREAD

**Issue by rvogelge** [hardillb/node-red-alexa-home-skill-web#81]
Hello I want to open again an issue regarding this error.
I have seen, that you have recommended to ignore as there will be a reconnect afterward.
Yes it is so, but in my configuration, this error appears  approx. every 5 seconds and the reconnect takes another 2-3 seconds. This means 1/3 of the time, Alexa commands can not be executed and Alexa complains that service is not available. 
My node red is running on Raspbian wheezy, Alexa and the Raspi are conected to the same AP, wireless connection is strong.
So do you have any other hints then just to ignore this error?
Thank you

**Comment by hardillb** [comment]
This had nothing to do with the error. 

You must have multiple instances signed in with the same username. Either different Node-RED instances or multiple config nodes.

You can only have one instance per username.

Make sure that you only have one config node and that all the device nodes are sharing the same one

**Comment by hardillb** [comment]
Actually thinking about this some more (last update was half way up a mountain on my bike) if you are getting that error repeated (with both port 8883 & 1883), then it implies your network won't allow outbound MQTT connections. If this is the case then this node will never work.

What can you tell me about your network, is it home broadband or an office network? Is it behind a firewall? Do you need to use a proxy to access the web?

**Comment by rvogelge** [comment]
Hi Ben, thanks for your fast feedback.
Actually, it was your first assumption. I had another instance of node red for testing with a second config note. So deleting this instance fixed my problem.
My network is a home broadband and actually outbound MQTT should work. And I only get this error for port 8883, 1883 works fine
And now I do get this error only after a Deploy in Node Red. So thats OK
Thank you very much and have a nice weekend.
I will start the weekend with a bike ride as well ;-)
