### ISSUE TITLE
Sorting Devices

### ISSUE THREAD

**Issue by DrinkALotDave** [hardillb/node-red-alexa-home-skill-web#83]
Please sort the devices on the web-interface by name.
It makes it easier to find a certain one.

**Comment by hardillb** [comment]
They are sorted by the order they are created, seams like as good a choice as any

**Comment by DrinkALotDave** [comment]
@hardillb: 
Well, if you have about 45 devices it is hard to find a certain one.
Do you remember in which order you created them?
By the way, they are not sorted in the order thy were created,
if they were, the device I created should be in position 45, not 4 ;-)
