### ISSUE TITLE
I can't receive reset password mail

### ISSUE THREAD

**Issue by jcf06010** [hardillb/node-red-alexa-home-skill-web#85]
If you have misplaced your password click here<-- submit e-mail adress,then Home come again. I wait long time ago,No mail from Node-RED Alexa Home.

**Comment by hardillb** [comment]
What is your username?

**Comment by hardillb** [comment]
Fixed, I'd messed something up with my mail server when I moved it a couple of days ago.

If you hit the link again it should work

**Comment by jcf06010** [comment]
Thank you!  I receive reset password mail.  Then I set new password,and I can login!
