### ISSUE TITLE
Bug/Crash 

### ISSUE THREAD

**Issue by Seymour77** [hardillb/node-red-alexa-home-skill-web#86]
Hi there
I’ve been using node-red (now at 0.20.7) in a raspberry pi 3 and pi4 with node-red-contrib-alexa-home-skill, node-red-contrib-mdashboard and node-red-contrib-knx-easy with 40 nodes to integrate my knx net with alexa and for more than 1 year i had not any issues, since 1 month ago when every few hours (24/48h) it stops working: not a raspberry issue because it works and I can reach it from terminal and I even try with the new pi 4, node-red in online because i can reach it at localhost:1880, everything is updated and when i give a command to alexa she tells me “ok” like as everything is fine but doesn’t work.
In order to make it work i need to turnoff/on the rasp.

Here is a log example

26 Aug 10:54:35 - [info] Stopping flows
26 Aug 10:54:35 - [info] Stopped flows
26 Aug 10:54:35 - [info] Starting flows
26 Aug 10:54:35 - [info] Started flows
26 Aug 10:54:35 - [error] [alexa-home-conf:768ded0f.d86ee4] Error: connect ECONN REFUSED 34.240.81.189:8883
28 Aug 01:05:39 - [error] [knxEasy-config:c5d52a91.1c5bf8] timed out waiting for CONNECTIONSTATE_RESPONSE

Those errors used to be not a problem cause it still used to work and often i saw those errors even if it works.
However I can ping the knx interface and it's online, Nodered flows is online at localhost:1880 connected and working, everything seems fine but alexa doesn't work althoug she doesn't tell "there is a problem" as everything is fine but the only way I have to make it work again is to stop the flood, reboot raspberry e start again.

**Comment by hardillb** [comment]
The connection refused error can be ignored

`[error] [alexa-home-conf:768ded0f.d86ee4] Error: connect ECONN REFUSED 34.240.81.189:8883`

as long as it shows the green dot and connected 5 seconds later then it has connected to the other instance of the broker.

You mention having 2 pi's. You can only have one Node-RED instance connected to the service at a time per user. If you connect two then they will fight for access to the broker and repeatedly kick each other off. 

You need to make sure you totally remove the configuration from the Node-RED instance you are not using, this includes the config node.

**Comment by Seymour77** [comment]
Sorry my bad, I didn't tell you I changed my pi3 with pi4 and the pi3 is not connected anymore on my net and unplugged. 

Even when it does not work It shows green dot and connection in 5 seconds but alexa althoug tells me "ok" when i give a command, doesn't work while if I stop nodered she tells me "a problem has occurred with the device"

**Comment by hardillb** [comment]
If Alexa is replying with ok, then the messages are making it all the way to the input node and assuming the "Auto Acknowledge" box is ticked it is responding. So basically working properly.

Attach a debug node to the device's input node and see if you get anything out of it?

But as I said if Alexa says ok then the backend is all working properly and it sounds like the node is as well

**Comment by Seymour77** [comment]
Ok I've attached the debug node, next time it will show the bug I try and write again here, thank you

**Comment by Seymour77** [comment]
Ok this morning I have again the bug after few hours, this is the log, pretty much nothing, http is on and I've attached two screenshot to show green dot and debug working, alexa tells me OK but it doesn't work.

At this point after I do a Deploy, easyknx nodes have red dot, even if I stop nodered and start again from terminal it remains so.

Then i reboot raspberry and everything works again.  

What could possible be the problem?
Maybe the knxIP module?

![1](https://user-images.githubusercontent.com/54628542/64002802-370a2000-cb0b-11e9-8f61-269feaf8ba40.png)
![2](https://user-images.githubusercontent.com/54628542/64002803-370a2000-cb0b-11e9-93ea-372f1e866c5d.png)

**Comment by hardillb** [comment]
Ok, so the Alexa stuff is all working so this has to be a problem with something else, given the error in the first log you posted it is probably the knx stuff
