### ISSUE TITLE
Firefox 68.0.2 (64-bit) and lack of config

### ISSUE THREAD

**Issue by ashleydrees** [hardillb/node-red-alexa-home-skill-web#87]
I have just had a Micro SD die and I was re-building my openhab (pi) setup.

When installing node-red-contrib-alexa-home-skill using Firefox 68.0.2 I was unable to see the config in the  alexa-config node... I can only see 
 Name and Type.

When I switched to Chrome everything was as listed in your documentation, the screenshot is from Firefox.  This is on a MBP running Mojave.

![Screenshot 2019-09-02 at 12 16 48](https://user-images.githubusercontent.com/365650/64111083-b69e2600-cd7b-11e9-8fb0-b37f8558041d.png)

**Comment by hardillb** [comment]
Please supply the version of Node-RED and nodejs you are using.

Also worth checking the Firefox console for any errors

**Comment by ashleydrees** [comment]
So I went back to firefox to turn on the debug and console and then opened an "Alexa Home" node and all the relevant bits were there.  I had just configured the connection in chrome so everything was working.

To try and clear this up earlier I had de-installed anything linked to Alexa and re-installed ONLY the node-red-contrib-alexa-home-skill - is it possible that one of the "other" alexa tools was cached in the firefox browser causing this loss of facility - name conflict or some such similar..

Node-Red 0.20.7: Maintenance Release
nodejs v10.16.3

**Comment by hardillb** [comment]
That is the most likely case.
