### ISSUE TITLE
Correction to Documentation

### ISSUE THREAD

**Issue by Bra1nK** [hardillb/node-red-alexa-home-skill-web#88]
https://alexa-node-red.bm.hardill.me.uk/docs 
The payload for a TurnOffRequest is false, not true
GetTargetTemperatureRequests should be GetTargetTemperatureRequest

**Comment by hardillb** [comment]
Feel free to raise a pull request to fix it.

**Comment by Bra1nK** [comment]
Ok will do

On 16 September 2019 20:18:05 BST, Ben Hardill <notifications@github.com> wrote:
>Feel free to raise a pull request to fix it.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/hardillb/node-red-alexa-home-skill-web/issues/88#issuecomment-531919089

-- 
Sent from my Samsung S9 Plus with K9 Mail
