### ISSUE TITLE
alexa says Device unresponsive after switching of the lights

### ISSUE THREAD

**Issue by zaid-kamil** [hardillb/node-red-alexa-home-skill-web#94]
i have done all the steps,
and when i say turn red light on, it works 
but when i say turn red light off , it switches off the light and then say red light is unresponsive.
So its the response msg of alexa which is the issue.

**Comment by hardillb** [comment]
There is no where near enough information here for me to be able to help.

Supply details of your flow, your username and versions of everything.

**Comment by zaid-kamil** [comment]
thanks for the reply.
