### ISSUE TITLE
Disconnection ...

### ISSUE THREAD

**Issue by anwar3000** [hardillb/node-red-alexa-home-skill-web#96]
Error: connect ECONNREFUSED 34.240.81.189:8883

Any solution for this error, i tried all the options but no success yet.
This issue started last week..

**Comment by hardillb** [comment]
You really need to give a LOT more information if you want help.

Are you seeing the message just once, or repeating?

What did you change (did you add more nodes, move to a new Node-RED deployment)?

**Comment by anwar3000** [comment]
I was working perfectly for the past 1 year or more, recently just few days onwards the issue started
> Only one instant is running 
> I tried with a new account same issue
> Yes this error continues minimum 2 error in a minute.
> No changes done..  same like before

**Comment by hardillb** [comment]
> Yes this error continues minimum 2 error in a minute.

I don't understand this line, do you mean that you get the same message every 2 mins?

**Comment by anwar3000** [comment]
every 30~40 second one error

**Comment by hardillb** [comment]
2 things

1. is the message exactly the same each time or does the port number change between 8883 and 1883?

2. Double check that you only have 1 config node (you can list all the config nodes by clicking on the hamburger menu and selecting "configuration nodes"

**Comment by anwar3000** [comment]
"Error: connect ECONNREFUSED 34.240.81.189:8883"   only this message no change same 8883 port

Yes checked, only one node

**Comment by hardillb** [comment]
I am not seeing you even try to connect to the backend with either username, so this is most likely a problem with your device not being able to reach the AWS instance that the broker is running on.

Check if you can ping 34.240.81.189 from the machine running Node-RED

**Comment by anwar3000** [comment]
64 bytes from 34.240.81.189: icmp_seq=31 ttl=229 time=138 ms
64 bytes from 34.240.81.189: icmp_seq=32 ttl=229 time=138 ms

**Comment by anwar3000** [comment]
it showing the devices list, that means it connected properly 
Below status is disconnecting  and after few seconds reconnecting

**Comment by anwar3000** [comment]
Now it seems like connected..

**Comment by hardillb** [comment]
> it showing the devices list, that means it connected properly

No it doesn't, the system is made up of 2 parts, a HTTP server and a MQTT broker.

You are failing to connect to the MQTT broker.

**Comment by anwar3000** [comment]
Now the below status green, but no response 
My alexa gives reply OK

**Comment by anwar3000** [comment]
I think something somewhere wrong, might be from my side
let me sleep on it, 
1000 Thanks for your awesome support.
I would like to discuss something about this, can u please share ur email

**Comment by hardillb** [comment]
No, but you can find me on Node-RED slack
