### ISSUE TITLE
Temperature response doesn't support decimal point

### ISSUE THREAD

**Issue by smcgann99** [hardillb/node-red-alexa-home-skill-web#97]
When setting temperature to a decimal value the alexa spoken response is rounded up or down.

In the example below alexa respondes heating is set to 16 even though 15.5 was requested.
But using GetTargetTemperatureRequest replies 15.5 as expected ?

Heating : msg : Object
object
topic: "Heating"
name: "Heating"
_messageId: "e668d3d4-8ffb-4e89-a172-0837ae61ab47"
_applianceId: "56840"
_confId: "a4d2ae82.5072a"
command: "SetTargetTemperatureRequest"
extraInfo: object
payload: 15.5
_msgid: "9fd8f0cc.2dcb8"

Heating : msg : Object
object
topic: "Heating"
name: "Heating"
_messageId: "e668d3d4-8ffb-4e89-a172-0837ae61ab47"
_applianceId: "56840"
_confId: "a4d2ae82.5072a"
command: "SetTargetTemperatureRequest"
extraInfo: object
payload: true
_msgid: "9fd8f0cc.2dcb8"
extra: object
targetTemperature: object
value: 15.5

**Comment by hardillb** [comment]
How the responses are verbalised is all controlled by Amazon on the backend. If it is rounding up/down from the actual value presented there is nothing you can do about it.
