### ISSUE TITLE
Device not emitting TurnOffRequest events anymore

### ISSUE THREAD

**Issue by forry2** [hardillb/node-red-alexa-home-skill-web#99]
I had several devices configured in my homeplace and your Alexa skill installed and running ok since months. All of a sudden, on one single device the TurnOffRequest event is not emitted anymore, my alexa just says "ok" when I tell her to turn that device off. Only TurnOnRequest events are managed and detected, and only on that particular device

**Comment by hardillb** [comment]
There is no useful information here that I can use to even start to look at this.

 1. What is your username?
 2. What is the name of the device that you are having problems with?
 3. What did you change?
 4. What debugging have you done? e.g. have you connected a debug node to the Alexa input node to see what messages are being emitted.
 5. What version of NodeJS, Node-RED and the Alexa Node do you have installed?

If you want help you have to supply at least some information for me to work with.

**Comment by forry2** [comment]
You're right, I didn't know where to start from.
1. forry2
2. casa
3. nothing....
4. connected a debug node to the alexa input node and check what comes out
of it
5. nodeJs v8.16.2, node Red v0.20.8, node-red-contrib-alexa-home-skill
v0.1.17



Sorry, and thanks again for your help

roberto

Il giorno ven 17 apr 2020 alle ore 08:37 Ben Hardill <
notifications@github.com> ha scritto:

**Comment by hardillb** [comment]
Just saying you've connected a debug node doesn't really help me either, showing some sample output would be useful. Also have you looked in the Node-RED log to see if anything is being printed to the console when you ask to turn that device on?

What happens if you try to turn this device on/off from the Alexa mobile app rather than from an echo device?

I've also set up some logging to track your devices while we look at this. So please try to turn this device on/off a few times then do the following steps and try again.

- removing the device
- asking Alexa to sync devices
- recreating the device
- deleting the input node in node-red and re-adding it (since the device will now have a new id)
- asking Alexa to sync devices again

**Comment by forry2** [comment]
Thanks Ben!

This is the configuration I am running:

[image: immagine.png]

"casa" isn't really a device, it's more of an endpoint to order all the
devices to turn on and off (through MQTT queues)
I do have a "Casa" group on Alexa mobile app, but nothing happens on your
node when I turn casa on and off from the Alexa mobile application



I followed your 5-bullets list. Now, when I ask to turn casa off, Alexa
says "ok" and does nothing, nor anything comes out of the device node on
node red. When I say to turn casa on, Alexa says it found more than one
device called "casa".
I am kinda confused here :D

Il giorno ven 17 apr 2020 alle ore 15:07 Ben Hardill <
notifications@github.com> ha scritto:

**Comment by hardillb** [comment]
Images attached to email responses to ticket updates do not get included in the issue

It's really not clear what you mean by "I have a group on the Alexa App", but if you have created a group of devices in the Alexa app called "cassa" then this will clash with the virtual device in this service and Amazon will not know where to send the commands.

You need to remove the group from the Alexa app then comands will flow to the virtual device.

**Comment by forry2** [comment]
No luck, Ben. I removed the Casa group from ìAlexa mobile app, then deleted
and recreated the device on your website. It still behaves like before: no
action but an "ok" when I ask to turn Casa off, a warning message saying
that more than one "Casa" device is present when I ask to turn Casa on

Il giorno ven 17 apr 2020 alle ore 15:32 Ben Hardill <
notifications@github.com> ha scritto:

**Comment by hardillb** [comment]
Delete the device on the service. Then make sure you request a Sync Devices.

Then open the mobile app and look on the devices tab.

First if you have a group called "Casa" like "Bedroom" or "Livingroom" in the following image:

![Screenshot_20200417-145716](https://user-images.githubusercontent.com/1800845/79577247-4f3fa700-80bc-11ea-877e-cc8217e547c7.png)

This will not work ask it will clash with the device name.

Second look at the full list of devices (from the list of devices at the top of the screen above, scroll the boxes to the left and there should be a "All devices" button). 

![Screenshot_20200417-150001](https://user-images.githubusercontent.com/1800845/79577745-17852f00-80bd-11ea-9032-ebd567b5302f.png)


Look on that list for any devices called "Casa". If there are pick it and then click on the gear in the top right hand corner to bring up the details it will then show you which service it came from. It should not be from Node-RED if you have deleted it and sync'd earlier. If it is still there and from Node-RED you can use the trash can icon to remove it again (if for some reason there are multiple delete them all)

At the moment none of the commands are being sent to my service, so all of this is on Amazon's side. If you manage to get all the versions of Casa removed from your account you can try adding it back in the service and triggering another sync (and then re-adding it to the Node-RED flow), but until you can convince Alexa that there is only one virtual device called Casa and no clashing groups there is nothing else I can do.

**Comment by forry2** [comment]
I manged to create another virtual device called "tutto" (means
"everything"). I can switch it on and off from the alexa app and it
correctly emits the TurnOnRequest and  TurnOffRequest messages. It doesn't
work with voice commands, as it only emits the TurnOnRequest message when I
ask to switch tutto on, but nothing happens on the off voice command

Il giorno ven 17 apr 2020 alle ore 16:09 Ben Hardill <
notifications@github.com> ha scritto:

**Comment by hardillb** [comment]
Best I can guess is that "Everything" and "House" are probably reserved words or just things that the Italian language model doesn't work well with.

I'm going to close this as it's all upstream with Amazon and nothing I have any control over.
